-- 充填率チェック: jvd_se (70カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_se' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(wakuban) AS cnt_wakuban,
    ROUND(COUNT(wakuban)::NUMERIC / COUNT(*) * 100, 2) AS rate_wakuban,
    COUNT(umaban) AS cnt_umaban,
    ROUND(COUNT(umaban)::NUMERIC / COUNT(*) * 100, 2) AS rate_umaban,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(umakigo_code) AS cnt_umakigo_code,
    ROUND(COUNT(umakigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_umakigo_code,
    COUNT(seibetsu_code) AS cnt_seibetsu_code,
    ROUND(COUNT(seibetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seibetsu_code,
    COUNT(hinshu_code) AS cnt_hinshu_code,
    ROUND(COUNT(hinshu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_hinshu_code,
    COUNT(moshoku_code) AS cnt_moshoku_code,
    ROUND(COUNT(moshoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_moshoku_code,
    COUNT(barei) AS cnt_barei,
    ROUND(COUNT(barei)::NUMERIC / COUNT(*) * 100, 2) AS rate_barei,
    COUNT(tozai_shozoku_code) AS cnt_tozai_shozoku_code,
    ROUND(COUNT(tozai_shozoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tozai_shozoku_code,
    COUNT(chokyoshi_code) AS cnt_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_code,
    COUNT(chokyoshimei_ryakusho) AS cnt_chokyoshimei_ryakusho,
    ROUND(COUNT(chokyoshimei_ryakusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei_ryakusho,
    COUNT(banushi_code) AS cnt_banushi_code,
    ROUND(COUNT(banushi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushi_code,
    COUNT(banushimei) AS cnt_banushimei,
    ROUND(COUNT(banushimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushimei,
    COUNT(fukushoku_hyoji) AS cnt_fukushoku_hyoji,
    ROUND(COUNT(fukushoku_hyoji)::NUMERIC / COUNT(*) * 100, 2) AS rate_fukushoku_hyoji,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(futan_juryo) AS cnt_futan_juryo,
    ROUND(COUNT(futan_juryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_futan_juryo,
    COUNT(futan_juryo_henkomae) AS cnt_futan_juryo_henkomae,
    ROUND(COUNT(futan_juryo_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_futan_juryo_henkomae,
    COUNT(blinker_shiyo_kubun) AS cnt_blinker_shiyo_kubun,
    ROUND(COUNT(blinker_shiyo_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_blinker_shiyo_kubun,
    COUNT(yobi_2) AS cnt_yobi_2,
    ROUND(COUNT(yobi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_2,
    COUNT(kishu_code) AS cnt_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code,
    COUNT(kishu_code_henkomae) AS cnt_kishu_code_henkomae,
    ROUND(COUNT(kishu_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code_henkomae,
    COUNT(kishumei_ryakusho) AS cnt_kishumei_ryakusho,
    ROUND(COUNT(kishumei_ryakusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei_ryakusho,
    COUNT(kishumei_ryakusho_henkomae) AS cnt_kishumei_ryakusho_henkomae,
    ROUND(COUNT(kishumei_ryakusho_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei_ryakusho_henkomae,
    COUNT(kishu_minarai_code) AS cnt_kishu_minarai_code,
    ROUND(COUNT(kishu_minarai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_minarai_code,
    COUNT(kishu_minarai_code_henkomae) AS cnt_kishu_minarai_code_henkomae,
    ROUND(COUNT(kishu_minarai_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_minarai_code_henkomae,
    COUNT(bataiju) AS cnt_bataiju,
    ROUND(COUNT(bataiju)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju,
    COUNT(zogen_fugo) AS cnt_zogen_fugo,
    ROUND(COUNT(zogen_fugo)::NUMERIC / COUNT(*) * 100, 2) AS rate_zogen_fugo,
    COUNT(zogen_sa) AS cnt_zogen_sa,
    ROUND(COUNT(zogen_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_zogen_sa,
    COUNT(ijo_kubun_code) AS cnt_ijo_kubun_code,
    ROUND(COUNT(ijo_kubun_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_ijo_kubun_code,
    COUNT(nyusen_juni) AS cnt_nyusen_juni,
    ROUND(COUNT(nyusen_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_nyusen_juni,
    COUNT(kakutei_chakujun) AS cnt_kakutei_chakujun,
    ROUND(COUNT(kakutei_chakujun)::NUMERIC / COUNT(*) * 100, 2) AS rate_kakutei_chakujun,
    COUNT(dochaku_kubun) AS cnt_dochaku_kubun,
    ROUND(COUNT(dochaku_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_dochaku_kubun,
    COUNT(dochaku_tosu) AS cnt_dochaku_tosu,
    ROUND(COUNT(dochaku_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_dochaku_tosu,
    COUNT(soha_time) AS cnt_soha_time,
    ROUND(COUNT(soha_time)::NUMERIC / COUNT(*) * 100, 2) AS rate_soha_time,
    COUNT(chakusa_code_1) AS cnt_chakusa_code_1,
    ROUND(COUNT(chakusa_code_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_chakusa_code_1,
    COUNT(chakusa_code_2) AS cnt_chakusa_code_2,
    ROUND(COUNT(chakusa_code_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_chakusa_code_2,
    COUNT(chakusa_code_3) AS cnt_chakusa_code_3,
    ROUND(COUNT(chakusa_code_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_chakusa_code_3,
    COUNT(corner_1) AS cnt_corner_1,
    ROUND(COUNT(corner_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_1,
    COUNT(corner_2) AS cnt_corner_2,
    ROUND(COUNT(corner_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_2,
    COUNT(corner_3) AS cnt_corner_3,
    ROUND(COUNT(corner_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_3,
    COUNT(corner_4) AS cnt_corner_4,
    ROUND(COUNT(corner_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_4,
    COUNT(tansho_odds) AS cnt_tansho_odds,
    ROUND(COUNT(tansho_odds)::NUMERIC / COUNT(*) * 100, 2) AS rate_tansho_odds,
    COUNT(tansho_ninkijun) AS cnt_tansho_ninkijun,
    ROUND(COUNT(tansho_ninkijun)::NUMERIC / COUNT(*) * 100, 2) AS rate_tansho_ninkijun,
    COUNT(kakutoku_honshokin) AS cnt_kakutoku_honshokin,
    ROUND(COUNT(kakutoku_honshokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_kakutoku_honshokin,
    COUNT(kakutoku_fukashokin) AS cnt_kakutoku_fukashokin,
    ROUND(COUNT(kakutoku_fukashokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_kakutoku_fukashokin,
    COUNT(yobi_3) AS cnt_yobi_3,
    ROUND(COUNT(yobi_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_3,
    COUNT(yobi_4) AS cnt_yobi_4,
    ROUND(COUNT(yobi_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4,
    COUNT(kohan_4f) AS cnt_kohan_4f,
    ROUND(COUNT(kohan_4f)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_4f,
    COUNT(kohan_3f) AS cnt_kohan_3f,
    ROUND(COUNT(kohan_3f)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f,
    COUNT(aiteuma_joho_1) AS cnt_aiteuma_joho_1,
    ROUND(COUNT(aiteuma_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_aiteuma_joho_1,
    COUNT(aiteuma_joho_2) AS cnt_aiteuma_joho_2,
    ROUND(COUNT(aiteuma_joho_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_aiteuma_joho_2,
    COUNT(aiteuma_joho_3) AS cnt_aiteuma_joho_3,
    ROUND(COUNT(aiteuma_joho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_aiteuma_joho_3,
    COUNT(time_sa) AS cnt_time_sa,
    ROUND(COUNT(time_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_sa,
    COUNT(record_koshin_kubun) AS cnt_record_koshin_kubun,
    ROUND(COUNT(record_koshin_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_koshin_kubun,
    COUNT(mining_kubun) AS cnt_mining_kubun,
    ROUND(COUNT(mining_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_kubun,
    COUNT(yoso_soha_time) AS cnt_yoso_soha_time,
    ROUND(COUNT(yoso_soha_time)::NUMERIC / COUNT(*) * 100, 2) AS rate_yoso_soha_time,
    COUNT(yoso_gosa_plus) AS cnt_yoso_gosa_plus,
    ROUND(COUNT(yoso_gosa_plus)::NUMERIC / COUNT(*) * 100, 2) AS rate_yoso_gosa_plus,
    COUNT(yoso_gosa_minus) AS cnt_yoso_gosa_minus,
    ROUND(COUNT(yoso_gosa_minus)::NUMERIC / COUNT(*) * 100, 2) AS rate_yoso_gosa_minus,
    COUNT(yoso_juni) AS cnt_yoso_juni,
    ROUND(COUNT(yoso_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_yoso_juni,
    COUNT(kyakushitsu_hantei) AS cnt_kyakushitsu_hantei,
    ROUND(COUNT(kyakushitsu_hantei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyakushitsu_hantei
FROM jvd_se
WHERE kaisai_nen BETWEEN '2016' AND '2025'
;