-- 充填率チェック: jvd_jc (20カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_jc' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(happyo_tsukihi_jifun) AS cnt_happyo_tsukihi_jifun,
    ROUND(COUNT(happyo_tsukihi_jifun)::NUMERIC / COUNT(*) * 100, 2) AS rate_happyo_tsukihi_jifun,
    COUNT(umaban) AS cnt_umaban,
    ROUND(COUNT(umaban)::NUMERIC / COUNT(*) * 100, 2) AS rate_umaban,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(futan_juryo) AS cnt_futan_juryo,
    ROUND(COUNT(futan_juryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_futan_juryo,
    COUNT(kishu_code) AS cnt_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code,
    COUNT(kishumei) AS cnt_kishumei,
    ROUND(COUNT(kishumei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei,
    COUNT(kishu_minarai_code) AS cnt_kishu_minarai_code,
    ROUND(COUNT(kishu_minarai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_minarai_code,
    COUNT(futan_juryo_henkomae) AS cnt_futan_juryo_henkomae,
    ROUND(COUNT(futan_juryo_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_futan_juryo_henkomae,
    COUNT(kishu_code_henkomae) AS cnt_kishu_code_henkomae,
    ROUND(COUNT(kishu_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code_henkomae,
    COUNT(kishumei_henkomae) AS cnt_kishumei_henkomae,
    ROUND(COUNT(kishumei_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei_henkomae,
    COUNT(kishu_minarai_code_henkomae) AS cnt_kishu_minarai_code_henkomae,
    ROUND(COUNT(kishu_minarai_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_minarai_code_henkomae
FROM jvd_jc
;