-- 充填率チェック: jvd_ck (106カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_ck' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(heichi_honshokin_ruikei) AS cnt_heichi_honshokin_ruikei,
    ROUND(COUNT(heichi_honshokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_heichi_honshokin_ruikei,
    COUNT(shogai_honshokin_ruikei) AS cnt_shogai_honshokin_ruikei,
    ROUND(COUNT(shogai_honshokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_honshokin_ruikei,
    COUNT(heichi_fukashokin_ruikei) AS cnt_heichi_fukashokin_ruikei,
    ROUND(COUNT(heichi_fukashokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_heichi_fukashokin_ruikei,
    COUNT(shogai_fukashokin_ruikei) AS cnt_shogai_fukashokin_ruikei,
    ROUND(COUNT(shogai_fukashokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_fukashokin_ruikei,
    COUNT(heichi_shutokushokin_ruikei) AS cnt_heichi_shutokushokin_ruikei,
    ROUND(COUNT(heichi_shutokushokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_heichi_shutokushokin_ruikei,
    COUNT(shogai_shutokushokin_ruikei) AS cnt_shogai_shutokushokin_ruikei,
    ROUND(COUNT(shogai_shutokushokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_shutokushokin_ruikei,
    COUNT(sogo) AS cnt_sogo,
    ROUND(COUNT(sogo)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo,
    COUNT(chuo_gokei) AS cnt_chuo_gokei,
    ROUND(COUNT(chuo_gokei)::NUMERIC / COUNT(*) * 100, 2) AS rate_chuo_gokei,
    COUNT(shiba_choku) AS cnt_shiba_choku,
    ROUND(COUNT(shiba_choku)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_choku,
    COUNT(shiba_migi) AS cnt_shiba_migi,
    ROUND(COUNT(shiba_migi)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_migi,
    COUNT(shiba_hidari) AS cnt_shiba_hidari,
    ROUND(COUNT(shiba_hidari)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_hidari,
    COUNT(dirt_choku) AS cnt_dirt_choku,
    ROUND(COUNT(dirt_choku)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_choku,
    COUNT(dirt_migi) AS cnt_dirt_migi,
    ROUND(COUNT(dirt_migi)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_migi,
    COUNT(dirt_hidari) AS cnt_dirt_hidari,
    ROUND(COUNT(dirt_hidari)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_hidari,
    COUNT(shogai) AS cnt_shogai,
    ROUND(COUNT(shogai)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai,
    COUNT(shiba_ryo) AS cnt_shiba_ryo,
    ROUND(COUNT(shiba_ryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_ryo,
    COUNT(shiba_yayaomo) AS cnt_shiba_yayaomo,
    ROUND(COUNT(shiba_yayaomo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_yayaomo,
    COUNT(shiba_omo) AS cnt_shiba_omo,
    ROUND(COUNT(shiba_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_omo,
    COUNT(shiba_furyo) AS cnt_shiba_furyo,
    ROUND(COUNT(shiba_furyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_furyo,
    COUNT(dirt_ryo) AS cnt_dirt_ryo,
    ROUND(COUNT(dirt_ryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_ryo,
    COUNT(dirt_yayaomo) AS cnt_dirt_yayaomo,
    ROUND(COUNT(dirt_yayaomo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_yayaomo,
    COUNT(dirt_omo) AS cnt_dirt_omo,
    ROUND(COUNT(dirt_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_omo,
    COUNT(dirt_furyo) AS cnt_dirt_furyo,
    ROUND(COUNT(dirt_furyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_furyo,
    COUNT(shogai_ryo) AS cnt_shogai_ryo,
    ROUND(COUNT(shogai_ryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_ryo,
    COUNT(shogai_yayaomo) AS cnt_shogai_yayaomo,
    ROUND(COUNT(shogai_yayaomo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_yayaomo,
    COUNT(shogai_omo) AS cnt_shogai_omo,
    ROUND(COUNT(shogai_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_omo,
    COUNT(shogai_furyo) AS cnt_shogai_furyo,
    ROUND(COUNT(shogai_furyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_furyo,
    COUNT(shiba_1200_ika) AS cnt_shiba_1200_ika,
    ROUND(COUNT(shiba_1200_ika)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_1200_ika,
    COUNT(shiba_1201_1400) AS cnt_shiba_1201_1400,
    ROUND(COUNT(shiba_1201_1400)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_1201_1400,
    COUNT(shiba_1401_1600) AS cnt_shiba_1401_1600,
    ROUND(COUNT(shiba_1401_1600)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_1401_1600,
    COUNT(shiba_1601_1800) AS cnt_shiba_1601_1800,
    ROUND(COUNT(shiba_1601_1800)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_1601_1800,
    COUNT(shiba_1801_2000) AS cnt_shiba_1801_2000,
    ROUND(COUNT(shiba_1801_2000)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_1801_2000,
    COUNT(shiba_2001_2200) AS cnt_shiba_2001_2200,
    ROUND(COUNT(shiba_2001_2200)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_2001_2200,
    COUNT(shiba_2201_2400) AS cnt_shiba_2201_2400,
    ROUND(COUNT(shiba_2201_2400)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_2201_2400,
    COUNT(shiba_2401_2800) AS cnt_shiba_2401_2800,
    ROUND(COUNT(shiba_2401_2800)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_2401_2800,
    COUNT(shiba_2801_ijo) AS cnt_shiba_2801_ijo,
    ROUND(COUNT(shiba_2801_ijo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_2801_ijo,
    COUNT(dirt_1200_ika) AS cnt_dirt_1200_ika,
    ROUND(COUNT(dirt_1200_ika)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_1200_ika,
    COUNT(dirt_1201_1400) AS cnt_dirt_1201_1400,
    ROUND(COUNT(dirt_1201_1400)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_1201_1400,
    COUNT(dirt_1401_1600) AS cnt_dirt_1401_1600,
    ROUND(COUNT(dirt_1401_1600)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_1401_1600,
    COUNT(dirt_1601_1800) AS cnt_dirt_1601_1800,
    ROUND(COUNT(dirt_1601_1800)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_1601_1800,
    COUNT(dirt_1801_2000) AS cnt_dirt_1801_2000,
    ROUND(COUNT(dirt_1801_2000)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_1801_2000,
    COUNT(dirt_2001_2200) AS cnt_dirt_2001_2200,
    ROUND(COUNT(dirt_2001_2200)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_2001_2200,
    COUNT(dirt_2201_2400) AS cnt_dirt_2201_2400,
    ROUND(COUNT(dirt_2201_2400)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_2201_2400,
    COUNT(dirt_2401_2800) AS cnt_dirt_2401_2800,
    ROUND(COUNT(dirt_2401_2800)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_2401_2800,
    COUNT(dirt_2801_ijo) AS cnt_dirt_2801_ijo,
    ROUND(COUNT(dirt_2801_ijo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_2801_ijo,
    COUNT(shiba_sapporo) AS cnt_shiba_sapporo,
    ROUND(COUNT(shiba_sapporo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_sapporo,
    COUNT(shiba_hakodate) AS cnt_shiba_hakodate,
    ROUND(COUNT(shiba_hakodate)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_hakodate,
    COUNT(shiba_fukushima) AS cnt_shiba_fukushima,
    ROUND(COUNT(shiba_fukushima)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_fukushima,
    COUNT(shiba_niigata) AS cnt_shiba_niigata,
    ROUND(COUNT(shiba_niigata)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_niigata,
    COUNT(shiba_tokyo) AS cnt_shiba_tokyo,
    ROUND(COUNT(shiba_tokyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_tokyo,
    COUNT(shiba_nakayama) AS cnt_shiba_nakayama,
    ROUND(COUNT(shiba_nakayama)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_nakayama,
    COUNT(shiba_chukyo) AS cnt_shiba_chukyo,
    ROUND(COUNT(shiba_chukyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_chukyo,
    COUNT(shiba_kyoto) AS cnt_shiba_kyoto,
    ROUND(COUNT(shiba_kyoto)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_kyoto,
    COUNT(shiba_hanshin) AS cnt_shiba_hanshin,
    ROUND(COUNT(shiba_hanshin)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_hanshin,
    COUNT(shiba_kokura) AS cnt_shiba_kokura,
    ROUND(COUNT(shiba_kokura)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_kokura,
    COUNT(dirt_sapporo) AS cnt_dirt_sapporo,
    ROUND(COUNT(dirt_sapporo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_sapporo,
    COUNT(dirt_hakodate) AS cnt_dirt_hakodate,
    ROUND(COUNT(dirt_hakodate)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_hakodate,
    COUNT(dirt_fukushima) AS cnt_dirt_fukushima,
    ROUND(COUNT(dirt_fukushima)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_fukushima,
    COUNT(dirt_niigata) AS cnt_dirt_niigata,
    ROUND(COUNT(dirt_niigata)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_niigata,
    COUNT(dirt_tokyo) AS cnt_dirt_tokyo,
    ROUND(COUNT(dirt_tokyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_tokyo,
    COUNT(dirt_nakayama) AS cnt_dirt_nakayama,
    ROUND(COUNT(dirt_nakayama)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_nakayama,
    COUNT(dirt_chukyo) AS cnt_dirt_chukyo,
    ROUND(COUNT(dirt_chukyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_chukyo,
    COUNT(dirt_kyoto) AS cnt_dirt_kyoto,
    ROUND(COUNT(dirt_kyoto)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_kyoto,
    COUNT(dirt_hanshin) AS cnt_dirt_hanshin,
    ROUND(COUNT(dirt_hanshin)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_hanshin,
    COUNT(dirt_kokura) AS cnt_dirt_kokura,
    ROUND(COUNT(dirt_kokura)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_kokura,
    COUNT(shogai_sapporo) AS cnt_shogai_sapporo,
    ROUND(COUNT(shogai_sapporo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_sapporo,
    COUNT(shogai_hakodate) AS cnt_shogai_hakodate,
    ROUND(COUNT(shogai_hakodate)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_hakodate,
    COUNT(shogai_fukushima) AS cnt_shogai_fukushima,
    ROUND(COUNT(shogai_fukushima)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_fukushima,
    COUNT(shogai_niigata) AS cnt_shogai_niigata,
    ROUND(COUNT(shogai_niigata)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_niigata,
    COUNT(shogai_tokyo) AS cnt_shogai_tokyo,
    ROUND(COUNT(shogai_tokyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_tokyo,
    COUNT(shogai_nakayama) AS cnt_shogai_nakayama,
    ROUND(COUNT(shogai_nakayama)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_nakayama,
    COUNT(shogai_chukyo) AS cnt_shogai_chukyo,
    ROUND(COUNT(shogai_chukyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_chukyo,
    COUNT(shogai_kyoto) AS cnt_shogai_kyoto,
    ROUND(COUNT(shogai_kyoto)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_kyoto,
    COUNT(shogai_hanshin) AS cnt_shogai_hanshin,
    ROUND(COUNT(shogai_hanshin)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_hanshin,
    COUNT(shogai_kokura) AS cnt_shogai_kokura,
    ROUND(COUNT(shogai_kokura)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_kokura,
    COUNT(kyakushitsu_keiko) AS cnt_kyakushitsu_keiko,
    ROUND(COUNT(kyakushitsu_keiko)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyakushitsu_keiko,
    COUNT(toroku_race_su) AS cnt_toroku_race_su,
    ROUND(COUNT(toroku_race_su)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_race_su,
    COUNT(kishu_code) AS cnt_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code,
    COUNT(kishumei) AS cnt_kishumei,
    ROUND(COUNT(kishumei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei,
    COUNT(seiseki_joho_kishu_1) AS cnt_seiseki_joho_kishu_1,
    ROUND(COUNT(seiseki_joho_kishu_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_kishu_1,
    COUNT(seiseki_joho_kishu_2) AS cnt_seiseki_joho_kishu_2,
    ROUND(COUNT(seiseki_joho_kishu_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_kishu_2,
    COUNT(chokyoshi_code) AS cnt_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_code,
    COUNT(chokyoshimei) AS cnt_chokyoshimei,
    ROUND(COUNT(chokyoshimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei,
    COUNT(seiseki_joho_chokyoshi_1) AS cnt_seiseki_joho_chokyoshi_1,
    ROUND(COUNT(seiseki_joho_chokyoshi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_chokyoshi_1,
    COUNT(seiseki_joho_chokyoshi_2) AS cnt_seiseki_joho_chokyoshi_2,
    ROUND(COUNT(seiseki_joho_chokyoshi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_chokyoshi_2,
    COUNT(banushi_code) AS cnt_banushi_code,
    ROUND(COUNT(banushi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushi_code,
    COUNT(banushimei_hojinkaku) AS cnt_banushimei_hojinkaku,
    ROUND(COUNT(banushimei_hojinkaku)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushimei_hojinkaku,
    COUNT(banushimei) AS cnt_banushimei,
    ROUND(COUNT(banushimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushimei,
    COUNT(seiseki_joho_banushi_1) AS cnt_seiseki_joho_banushi_1,
    ROUND(COUNT(seiseki_joho_banushi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_banushi_1,
    COUNT(seiseki_joho_banushi_2) AS cnt_seiseki_joho_banushi_2,
    ROUND(COUNT(seiseki_joho_banushi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_banushi_2,
    COUNT(seisansha_code) AS cnt_seisansha_code,
    ROUND(COUNT(seisansha_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seisansha_code,
    COUNT(seisanshamei_hojinkaku) AS cnt_seisanshamei_hojinkaku,
    ROUND(COUNT(seisanshamei_hojinkaku)::NUMERIC / COUNT(*) * 100, 2) AS rate_seisanshamei_hojinkaku,
    COUNT(seisanshamei) AS cnt_seisanshamei,
    ROUND(COUNT(seisanshamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_seisanshamei,
    COUNT(seiseki_joho_seisansha_1) AS cnt_seiseki_joho_seisansha_1,
    ROUND(COUNT(seiseki_joho_seisansha_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_seisansha_1,
    COUNT(seiseki_joho_seisansha_2) AS cnt_seiseki_joho_seisansha_2,
    ROUND(COUNT(seiseki_joho_seisansha_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_seisansha_2
FROM jvd_ck
WHERE kaisai_nen BETWEEN '2016' AND '2025'
;