-- 充填率チェック: jvd_hn (19カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_hn' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(hanshoku_toroku_bango) AS cnt_hanshoku_toroku_bango,
    ROUND(COUNT(hanshoku_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_hanshoku_toroku_bango,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(yobi_2) AS cnt_yobi_2,
    ROUND(COUNT(yobi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_2,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(bamei_hankaku_kana) AS cnt_bamei_hankaku_kana,
    ROUND(COUNT(bamei_hankaku_kana)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei_hankaku_kana,
    COUNT(bamei_eur) AS cnt_bamei_eur,
    ROUND(COUNT(bamei_eur)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei_eur,
    COUNT(seinen) AS cnt_seinen,
    ROUND(COUNT(seinen)::NUMERIC / COUNT(*) * 100, 2) AS rate_seinen,
    COUNT(seibetsu_code) AS cnt_seibetsu_code,
    ROUND(COUNT(seibetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seibetsu_code,
    COUNT(hinshu_code) AS cnt_hinshu_code,
    ROUND(COUNT(hinshu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_hinshu_code,
    COUNT(moshoku_code) AS cnt_moshoku_code,
    ROUND(COUNT(moshoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_moshoku_code,
    COUNT(mochikomi_kubun) AS cnt_mochikomi_kubun,
    ROUND(COUNT(mochikomi_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_mochikomi_kubun,
    COUNT(yunyu_nen) AS cnt_yunyu_nen,
    ROUND(COUNT(yunyu_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_yunyu_nen,
    COUNT(sanchimei) AS cnt_sanchimei,
    ROUND(COUNT(sanchimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_sanchimei,
    COUNT(ketto_joho_01a) AS cnt_ketto_joho_01a,
    ROUND(COUNT(ketto_joho_01a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_01a,
    COUNT(ketto_joho_02a) AS cnt_ketto_joho_02a,
    ROUND(COUNT(ketto_joho_02a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_02a
FROM jvd_hn
;