-- 充填率チェック: jvd_um (89カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_um' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(massho_kubun) AS cnt_massho_kubun,
    ROUND(COUNT(massho_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_massho_kubun,
    COUNT(toroku_nengappi) AS cnt_toroku_nengappi,
    ROUND(COUNT(toroku_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_nengappi,
    COUNT(massho_nengappi) AS cnt_massho_nengappi,
    ROUND(COUNT(massho_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_massho_nengappi,
    COUNT(seinengappi) AS cnt_seinengappi,
    ROUND(COUNT(seinengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_seinengappi,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(bamei_hankaku_kana) AS cnt_bamei_hankaku_kana,
    ROUND(COUNT(bamei_hankaku_kana)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei_hankaku_kana,
    COUNT(bamei_eur) AS cnt_bamei_eur,
    ROUND(COUNT(bamei_eur)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei_eur,
    COUNT(zaikyu_flag) AS cnt_zaikyu_flag,
    ROUND(COUNT(zaikyu_flag)::NUMERIC / COUNT(*) * 100, 2) AS rate_zaikyu_flag,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(umakigo_code) AS cnt_umakigo_code,
    ROUND(COUNT(umakigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_umakigo_code,
    COUNT(seibetsu_code) AS cnt_seibetsu_code,
    ROUND(COUNT(seibetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seibetsu_code,
    COUNT(hinshu_code) AS cnt_hinshu_code,
    ROUND(COUNT(hinshu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_hinshu_code,
    COUNT(moshoku_code) AS cnt_moshoku_code,
    ROUND(COUNT(moshoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_moshoku_code,
    COUNT(ketto_joho_01a) AS cnt_ketto_joho_01a,
    ROUND(COUNT(ketto_joho_01a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_01a,
    COUNT(ketto_joho_01b) AS cnt_ketto_joho_01b,
    ROUND(COUNT(ketto_joho_01b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_01b,
    COUNT(ketto_joho_02a) AS cnt_ketto_joho_02a,
    ROUND(COUNT(ketto_joho_02a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_02a,
    COUNT(ketto_joho_02b) AS cnt_ketto_joho_02b,
    ROUND(COUNT(ketto_joho_02b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_02b,
    COUNT(ketto_joho_03a) AS cnt_ketto_joho_03a,
    ROUND(COUNT(ketto_joho_03a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_03a,
    COUNT(ketto_joho_03b) AS cnt_ketto_joho_03b,
    ROUND(COUNT(ketto_joho_03b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_03b,
    COUNT(ketto_joho_04a) AS cnt_ketto_joho_04a,
    ROUND(COUNT(ketto_joho_04a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_04a,
    COUNT(ketto_joho_04b) AS cnt_ketto_joho_04b,
    ROUND(COUNT(ketto_joho_04b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_04b,
    COUNT(ketto_joho_05a) AS cnt_ketto_joho_05a,
    ROUND(COUNT(ketto_joho_05a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_05a,
    COUNT(ketto_joho_05b) AS cnt_ketto_joho_05b,
    ROUND(COUNT(ketto_joho_05b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_05b,
    COUNT(ketto_joho_06a) AS cnt_ketto_joho_06a,
    ROUND(COUNT(ketto_joho_06a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_06a,
    COUNT(ketto_joho_06b) AS cnt_ketto_joho_06b,
    ROUND(COUNT(ketto_joho_06b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_06b,
    COUNT(ketto_joho_07a) AS cnt_ketto_joho_07a,
    ROUND(COUNT(ketto_joho_07a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_07a,
    COUNT(ketto_joho_07b) AS cnt_ketto_joho_07b,
    ROUND(COUNT(ketto_joho_07b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_07b,
    COUNT(ketto_joho_08a) AS cnt_ketto_joho_08a,
    ROUND(COUNT(ketto_joho_08a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_08a,
    COUNT(ketto_joho_08b) AS cnt_ketto_joho_08b,
    ROUND(COUNT(ketto_joho_08b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_08b,
    COUNT(ketto_joho_09a) AS cnt_ketto_joho_09a,
    ROUND(COUNT(ketto_joho_09a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_09a,
    COUNT(ketto_joho_09b) AS cnt_ketto_joho_09b,
    ROUND(COUNT(ketto_joho_09b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_09b,
    COUNT(ketto_joho_10a) AS cnt_ketto_joho_10a,
    ROUND(COUNT(ketto_joho_10a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_10a,
    COUNT(ketto_joho_10b) AS cnt_ketto_joho_10b,
    ROUND(COUNT(ketto_joho_10b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_10b,
    COUNT(ketto_joho_11a) AS cnt_ketto_joho_11a,
    ROUND(COUNT(ketto_joho_11a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_11a,
    COUNT(ketto_joho_11b) AS cnt_ketto_joho_11b,
    ROUND(COUNT(ketto_joho_11b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_11b,
    COUNT(ketto_joho_12a) AS cnt_ketto_joho_12a,
    ROUND(COUNT(ketto_joho_12a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_12a,
    COUNT(ketto_joho_12b) AS cnt_ketto_joho_12b,
    ROUND(COUNT(ketto_joho_12b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_12b,
    COUNT(ketto_joho_13a) AS cnt_ketto_joho_13a,
    ROUND(COUNT(ketto_joho_13a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_13a,
    COUNT(ketto_joho_13b) AS cnt_ketto_joho_13b,
    ROUND(COUNT(ketto_joho_13b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_13b,
    COUNT(ketto_joho_14a) AS cnt_ketto_joho_14a,
    ROUND(COUNT(ketto_joho_14a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_14a,
    COUNT(ketto_joho_14b) AS cnt_ketto_joho_14b,
    ROUND(COUNT(ketto_joho_14b)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_14b,
    COUNT(tozai_shozoku_code) AS cnt_tozai_shozoku_code,
    ROUND(COUNT(tozai_shozoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tozai_shozoku_code,
    COUNT(chokyoshi_code) AS cnt_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_code,
    COUNT(chokyoshimei_ryakusho) AS cnt_chokyoshimei_ryakusho,
    ROUND(COUNT(chokyoshimei_ryakusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei_ryakusho,
    COUNT(shotai_chiikimei) AS cnt_shotai_chiikimei,
    ROUND(COUNT(shotai_chiikimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shotai_chiikimei,
    COUNT(seisansha_code) AS cnt_seisansha_code,
    ROUND(COUNT(seisansha_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seisansha_code,
    COUNT(seisanshamei) AS cnt_seisanshamei,
    ROUND(COUNT(seisanshamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_seisanshamei,
    COUNT(sanchimei) AS cnt_sanchimei,
    ROUND(COUNT(sanchimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_sanchimei,
    COUNT(banushi_code) AS cnt_banushi_code,
    ROUND(COUNT(banushi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushi_code,
    COUNT(banushimei) AS cnt_banushimei,
    ROUND(COUNT(banushimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushimei,
    COUNT(heichi_honshokin_ruikei) AS cnt_heichi_honshokin_ruikei,
    ROUND(COUNT(heichi_honshokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_heichi_honshokin_ruikei,
    COUNT(shogai_honshokin_ruikei) AS cnt_shogai_honshokin_ruikei,
    ROUND(COUNT(shogai_honshokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_honshokin_ruikei,
    COUNT(heichi_fukashokin_ruikei) AS cnt_heichi_fukashokin_ruikei,
    ROUND(COUNT(heichi_fukashokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_heichi_fukashokin_ruikei,
    COUNT(shogai_fukashokin_ruikei) AS cnt_shogai_fukashokin_ruikei,
    ROUND(COUNT(shogai_fukashokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_fukashokin_ruikei,
    COUNT(heichi_shutokushokin_ruikei) AS cnt_heichi_shutokushokin_ruikei,
    ROUND(COUNT(heichi_shutokushokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_heichi_shutokushokin_ruikei,
    COUNT(shogai_shutokushokin_ruikei) AS cnt_shogai_shutokushokin_ruikei,
    ROUND(COUNT(shogai_shutokushokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_shutokushokin_ruikei,
    COUNT(sogo) AS cnt_sogo,
    ROUND(COUNT(sogo)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo,
    COUNT(chuo_gokei) AS cnt_chuo_gokei,
    ROUND(COUNT(chuo_gokei)::NUMERIC / COUNT(*) * 100, 2) AS rate_chuo_gokei,
    COUNT(shiba_choku) AS cnt_shiba_choku,
    ROUND(COUNT(shiba_choku)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_choku,
    COUNT(shiba_migi) AS cnt_shiba_migi,
    ROUND(COUNT(shiba_migi)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_migi,
    COUNT(shiba_hidari) AS cnt_shiba_hidari,
    ROUND(COUNT(shiba_hidari)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_hidari,
    COUNT(dirt_choku) AS cnt_dirt_choku,
    ROUND(COUNT(dirt_choku)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_choku,
    COUNT(dirt_migi) AS cnt_dirt_migi,
    ROUND(COUNT(dirt_migi)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_migi,
    COUNT(dirt_hidari) AS cnt_dirt_hidari,
    ROUND(COUNT(dirt_hidari)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_hidari,
    COUNT(shogai) AS cnt_shogai,
    ROUND(COUNT(shogai)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai,
    COUNT(shiba_ryo) AS cnt_shiba_ryo,
    ROUND(COUNT(shiba_ryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_ryo,
    COUNT(shiba_yayaomo) AS cnt_shiba_yayaomo,
    ROUND(COUNT(shiba_yayaomo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_yayaomo,
    COUNT(shiba_omo) AS cnt_shiba_omo,
    ROUND(COUNT(shiba_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_omo,
    COUNT(shiba_furyo) AS cnt_shiba_furyo,
    ROUND(COUNT(shiba_furyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_furyo,
    COUNT(dirt_ryo) AS cnt_dirt_ryo,
    ROUND(COUNT(dirt_ryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_ryo,
    COUNT(dirt_yayaomo) AS cnt_dirt_yayaomo,
    ROUND(COUNT(dirt_yayaomo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_yayaomo,
    COUNT(dirt_omo) AS cnt_dirt_omo,
    ROUND(COUNT(dirt_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_omo,
    COUNT(dirt_furyo) AS cnt_dirt_furyo,
    ROUND(COUNT(dirt_furyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_furyo,
    COUNT(shogai_ryo) AS cnt_shogai_ryo,
    ROUND(COUNT(shogai_ryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_ryo,
    COUNT(shogai_yayaomo) AS cnt_shogai_yayaomo,
    ROUND(COUNT(shogai_yayaomo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_yayaomo,
    COUNT(shogai_omo) AS cnt_shogai_omo,
    ROUND(COUNT(shogai_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_omo,
    COUNT(shogai_furyo) AS cnt_shogai_furyo,
    ROUND(COUNT(shogai_furyo)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_furyo,
    COUNT(shiba_short) AS cnt_shiba_short,
    ROUND(COUNT(shiba_short)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_short,
    COUNT(shiba_middle) AS cnt_shiba_middle,
    ROUND(COUNT(shiba_middle)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_middle,
    COUNT(shiba_long) AS cnt_shiba_long,
    ROUND(COUNT(shiba_long)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiba_long,
    COUNT(dirt_short) AS cnt_dirt_short,
    ROUND(COUNT(dirt_short)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_short,
    COUNT(dirt_middle) AS cnt_dirt_middle,
    ROUND(COUNT(dirt_middle)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_middle,
    COUNT(dirt_long) AS cnt_dirt_long,
    ROUND(COUNT(dirt_long)::NUMERIC / COUNT(*) * 100, 2) AS rate_dirt_long,
    COUNT(kyakushitsu_keiko) AS cnt_kyakushitsu_keiko,
    ROUND(COUNT(kyakushitsu_keiko)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyakushitsu_keiko,
    COUNT(toroku_race_su) AS cnt_toroku_race_su,
    ROUND(COUNT(toroku_race_su)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_race_su
FROM jvd_um
;