-- 充填率チェック: jvd_ra (62カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_ra' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(yobi_code) AS cnt_yobi_code,
    ROUND(COUNT(yobi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_code,
    COUNT(tokubetsu_kyoso_bango) AS cnt_tokubetsu_kyoso_bango,
    ROUND(COUNT(tokubetsu_kyoso_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubetsu_kyoso_bango,
    COUNT(kyosomei_hondai) AS cnt_kyosomei_hondai,
    ROUND(COUNT(kyosomei_hondai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_hondai,
    COUNT(kyosomei_fukudai) AS cnt_kyosomei_fukudai,
    ROUND(COUNT(kyosomei_fukudai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_fukudai,
    COUNT(kyosomei_kakkonai) AS cnt_kyosomei_kakkonai,
    ROUND(COUNT(kyosomei_kakkonai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_kakkonai,
    COUNT(kyosomei_hondai_eur) AS cnt_kyosomei_hondai_eur,
    ROUND(COUNT(kyosomei_hondai_eur)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_hondai_eur,
    COUNT(kyosomei_fukudai_eur) AS cnt_kyosomei_fukudai_eur,
    ROUND(COUNT(kyosomei_fukudai_eur)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_fukudai_eur,
    COUNT(kyosomei_kakkonai_eur) AS cnt_kyosomei_kakkonai_eur,
    ROUND(COUNT(kyosomei_kakkonai_eur)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_kakkonai_eur,
    COUNT(kyosomei_ryakusho_10) AS cnt_kyosomei_ryakusho_10,
    ROUND(COUNT(kyosomei_ryakusho_10)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_ryakusho_10,
    COUNT(kyosomei_ryakusho_6) AS cnt_kyosomei_ryakusho_6,
    ROUND(COUNT(kyosomei_ryakusho_6)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_ryakusho_6,
    COUNT(kyosomei_ryakusho_3) AS cnt_kyosomei_ryakusho_3,
    ROUND(COUNT(kyosomei_ryakusho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_ryakusho_3,
    COUNT(kyosomei_kubun) AS cnt_kyosomei_kubun,
    ROUND(COUNT(kyosomei_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_kubun,
    COUNT(jusho_kaiji) AS cnt_jusho_kaiji,
    ROUND(COUNT(jusho_kaiji)::NUMERIC / COUNT(*) * 100, 2) AS rate_jusho_kaiji,
    COUNT(grade_code) AS cnt_grade_code,
    ROUND(COUNT(grade_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_grade_code,
    COUNT(grade_code_henkomae) AS cnt_grade_code_henkomae,
    ROUND(COUNT(grade_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_grade_code_henkomae,
    COUNT(kyoso_shubetsu_code) AS cnt_kyoso_shubetsu_code,
    ROUND(COUNT(kyoso_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_shubetsu_code,
    COUNT(kyoso_kigo_code) AS cnt_kyoso_kigo_code,
    ROUND(COUNT(kyoso_kigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_kigo_code,
    COUNT(juryo_shubetsu_code) AS cnt_juryo_shubetsu_code,
    ROUND(COUNT(juryo_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_juryo_shubetsu_code,
    COUNT(kyoso_joken_code_2sai) AS cnt_kyoso_joken_code_2sai,
    ROUND(COUNT(kyoso_joken_code_2sai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code_2sai,
    COUNT(kyoso_joken_code_3sai) AS cnt_kyoso_joken_code_3sai,
    ROUND(COUNT(kyoso_joken_code_3sai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code_3sai,
    COUNT(kyoso_joken_code_4sai) AS cnt_kyoso_joken_code_4sai,
    ROUND(COUNT(kyoso_joken_code_4sai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code_4sai,
    COUNT(kyoso_joken_code_5sai_ijo) AS cnt_kyoso_joken_code_5sai_ijo,
    ROUND(COUNT(kyoso_joken_code_5sai_ijo)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code_5sai_ijo,
    COUNT(kyoso_joken_code) AS cnt_kyoso_joken_code,
    ROUND(COUNT(kyoso_joken_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code,
    COUNT(kyoso_joken_meisho) AS cnt_kyoso_joken_meisho,
    ROUND(COUNT(kyoso_joken_meisho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_meisho,
    COUNT(kyori) AS cnt_kyori,
    ROUND(COUNT(kyori)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori,
    COUNT(kyori_henkomae) AS cnt_kyori_henkomae,
    ROUND(COUNT(kyori_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori_henkomae,
    COUNT(track_code) AS cnt_track_code,
    ROUND(COUNT(track_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_track_code,
    COUNT(track_code_henkomae) AS cnt_track_code_henkomae,
    ROUND(COUNT(track_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_track_code_henkomae,
    COUNT(course_kubun) AS cnt_course_kubun,
    ROUND(COUNT(course_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_course_kubun,
    COUNT(course_kubun_henkomae) AS cnt_course_kubun_henkomae,
    ROUND(COUNT(course_kubun_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_course_kubun_henkomae,
    COUNT(honshokin) AS cnt_honshokin,
    ROUND(COUNT(honshokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_honshokin,
    COUNT(honshokin_henkomae) AS cnt_honshokin_henkomae,
    ROUND(COUNT(honshokin_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_honshokin_henkomae,
    COUNT(fukashokin) AS cnt_fukashokin,
    ROUND(COUNT(fukashokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_fukashokin,
    COUNT(fukashokin_henkomae) AS cnt_fukashokin_henkomae,
    ROUND(COUNT(fukashokin_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_fukashokin_henkomae,
    COUNT(hasso_jikoku) AS cnt_hasso_jikoku,
    ROUND(COUNT(hasso_jikoku)::NUMERIC / COUNT(*) * 100, 2) AS rate_hasso_jikoku,
    COUNT(hasso_jikoku_henkomae) AS cnt_hasso_jikoku_henkomae,
    ROUND(COUNT(hasso_jikoku_henkomae)::NUMERIC / COUNT(*) * 100, 2) AS rate_hasso_jikoku_henkomae,
    COUNT(toroku_tosu) AS cnt_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_tosu,
    COUNT(shusso_tosu) AS cnt_shusso_tosu,
    ROUND(COUNT(shusso_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_shusso_tosu,
    COUNT(nyusen_tosu) AS cnt_nyusen_tosu,
    ROUND(COUNT(nyusen_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_nyusen_tosu,
    COUNT(tenko_code) AS cnt_tenko_code,
    ROUND(COUNT(tenko_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tenko_code,
    COUNT(babajotai_code_shiba) AS cnt_babajotai_code_shiba,
    ROUND(COUNT(babajotai_code_shiba)::NUMERIC / COUNT(*) * 100, 2) AS rate_babajotai_code_shiba,
    COUNT(babajotai_code_dirt) AS cnt_babajotai_code_dirt,
    ROUND(COUNT(babajotai_code_dirt)::NUMERIC / COUNT(*) * 100, 2) AS rate_babajotai_code_dirt,
    COUNT(lap_time) AS cnt_lap_time,
    ROUND(COUNT(lap_time)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time,
    COUNT(shogai_mile_time) AS cnt_shogai_mile_time,
    ROUND(COUNT(shogai_mile_time)::NUMERIC / COUNT(*) * 100, 2) AS rate_shogai_mile_time,
    COUNT(zenhan_3f) AS cnt_zenhan_3f,
    ROUND(COUNT(zenhan_3f)::NUMERIC / COUNT(*) * 100, 2) AS rate_zenhan_3f,
    COUNT(zenhan_4f) AS cnt_zenhan_4f,
    ROUND(COUNT(zenhan_4f)::NUMERIC / COUNT(*) * 100, 2) AS rate_zenhan_4f,
    COUNT(kohan_3f) AS cnt_kohan_3f,
    ROUND(COUNT(kohan_3f)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f,
    COUNT(kohan_4f) AS cnt_kohan_4f,
    ROUND(COUNT(kohan_4f)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_4f,
    COUNT(corner_tsuka_juni_1) AS cnt_corner_tsuka_juni_1,
    ROUND(COUNT(corner_tsuka_juni_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_tsuka_juni_1,
    COUNT(corner_tsuka_juni_2) AS cnt_corner_tsuka_juni_2,
    ROUND(COUNT(corner_tsuka_juni_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_tsuka_juni_2,
    COUNT(corner_tsuka_juni_3) AS cnt_corner_tsuka_juni_3,
    ROUND(COUNT(corner_tsuka_juni_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_tsuka_juni_3,
    COUNT(corner_tsuka_juni_4) AS cnt_corner_tsuka_juni_4,
    ROUND(COUNT(corner_tsuka_juni_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_tsuka_juni_4,
    COUNT(record_koshin_kubun) AS cnt_record_koshin_kubun,
    ROUND(COUNT(record_koshin_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_koshin_kubun
FROM jvd_ra
WHERE kaisai_nen BETWEEN '2016' AND '2025'
;