-- 充填率チェック: jvd_rc (24カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_rc' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(record_shikibetsu_kubun) AS cnt_record_shikibetsu_kubun,
    ROUND(COUNT(record_shikibetsu_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_shikibetsu_kubun,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(tokubetsu_kyoso_bango) AS cnt_tokubetsu_kyoso_bango,
    ROUND(COUNT(tokubetsu_kyoso_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubetsu_kyoso_bango,
    COUNT(kyosomei_hondai) AS cnt_kyosomei_hondai,
    ROUND(COUNT(kyosomei_hondai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_hondai,
    COUNT(grade_code) AS cnt_grade_code,
    ROUND(COUNT(grade_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_grade_code,
    COUNT(kyoso_shubetsu_code) AS cnt_kyoso_shubetsu_code,
    ROUND(COUNT(kyoso_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_shubetsu_code,
    COUNT(kyori) AS cnt_kyori,
    ROUND(COUNT(kyori)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori,
    COUNT(track_code) AS cnt_track_code,
    ROUND(COUNT(track_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_track_code,
    COUNT(record_kubun) AS cnt_record_kubun,
    ROUND(COUNT(record_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_kubun,
    COUNT(record_time) AS cnt_record_time,
    ROUND(COUNT(record_time)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_time,
    COUNT(tenko_code) AS cnt_tenko_code,
    ROUND(COUNT(tenko_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tenko_code,
    COUNT(babajotai_code_shiba) AS cnt_babajotai_code_shiba,
    ROUND(COUNT(babajotai_code_shiba)::NUMERIC / COUNT(*) * 100, 2) AS rate_babajotai_code_shiba,
    COUNT(babajotai_code_dirt) AS cnt_babajotai_code_dirt,
    ROUND(COUNT(babajotai_code_dirt)::NUMERIC / COUNT(*) * 100, 2) AS rate_babajotai_code_dirt,
    COUNT(record_hojiuma_joho_1) AS cnt_record_hojiuma_joho_1,
    ROUND(COUNT(record_hojiuma_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_hojiuma_joho_1,
    COUNT(record_hojiuma_joho_2) AS cnt_record_hojiuma_joho_2,
    ROUND(COUNT(record_hojiuma_joho_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_hojiuma_joho_2,
    COUNT(record_hojiuma_joho_3) AS cnt_record_hojiuma_joho_3,
    ROUND(COUNT(record_hojiuma_joho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_hojiuma_joho_3
FROM jvd_rc
;