-- 充填率チェック: jvd_sk (26カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_sk' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(seinengappi) AS cnt_seinengappi,
    ROUND(COUNT(seinengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_seinengappi,
    COUNT(seibetsu_code) AS cnt_seibetsu_code,
    ROUND(COUNT(seibetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seibetsu_code,
    COUNT(hinshu_code) AS cnt_hinshu_code,
    ROUND(COUNT(hinshu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_hinshu_code,
    COUNT(moshoku_code) AS cnt_moshoku_code,
    ROUND(COUNT(moshoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_moshoku_code,
    COUNT(mochikomi_kubun) AS cnt_mochikomi_kubun,
    ROUND(COUNT(mochikomi_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_mochikomi_kubun,
    COUNT(yunyu_nen) AS cnt_yunyu_nen,
    ROUND(COUNT(yunyu_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_yunyu_nen,
    COUNT(seisansha_code) AS cnt_seisansha_code,
    ROUND(COUNT(seisansha_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seisansha_code,
    COUNT(sanchimei) AS cnt_sanchimei,
    ROUND(COUNT(sanchimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_sanchimei,
    COUNT(ketto_joho_01a) AS cnt_ketto_joho_01a,
    ROUND(COUNT(ketto_joho_01a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_01a,
    COUNT(ketto_joho_02a) AS cnt_ketto_joho_02a,
    ROUND(COUNT(ketto_joho_02a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_02a,
    COUNT(ketto_joho_03a) AS cnt_ketto_joho_03a,
    ROUND(COUNT(ketto_joho_03a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_03a,
    COUNT(ketto_joho_04a) AS cnt_ketto_joho_04a,
    ROUND(COUNT(ketto_joho_04a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_04a,
    COUNT(ketto_joho_05a) AS cnt_ketto_joho_05a,
    ROUND(COUNT(ketto_joho_05a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_05a,
    COUNT(ketto_joho_06a) AS cnt_ketto_joho_06a,
    ROUND(COUNT(ketto_joho_06a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_06a,
    COUNT(ketto_joho_07a) AS cnt_ketto_joho_07a,
    ROUND(COUNT(ketto_joho_07a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_07a,
    COUNT(ketto_joho_08a) AS cnt_ketto_joho_08a,
    ROUND(COUNT(ketto_joho_08a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_08a,
    COUNT(ketto_joho_09a) AS cnt_ketto_joho_09a,
    ROUND(COUNT(ketto_joho_09a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_09a,
    COUNT(ketto_joho_10a) AS cnt_ketto_joho_10a,
    ROUND(COUNT(ketto_joho_10a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_10a,
    COUNT(ketto_joho_11a) AS cnt_ketto_joho_11a,
    ROUND(COUNT(ketto_joho_11a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_11a,
    COUNT(ketto_joho_12a) AS cnt_ketto_joho_12a,
    ROUND(COUNT(ketto_joho_12a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_12a,
    COUNT(ketto_joho_13a) AS cnt_ketto_joho_13a,
    ROUND(COUNT(ketto_joho_13a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_13a,
    COUNT(ketto_joho_14a) AS cnt_ketto_joho_14a,
    ROUND(COUNT(ketto_joho_14a)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_joho_14a
FROM jvd_sk
;