-- 充填率チェック: jvd_hr (158カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_hr' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(toroku_tosu) AS cnt_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_tosu,
    COUNT(shusso_tosu) AS cnt_shusso_tosu,
    ROUND(COUNT(shusso_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_shusso_tosu,
    COUNT(fuseiritsu_flag_tansho) AS cnt_fuseiritsu_flag_tansho,
    ROUND(COUNT(fuseiritsu_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_tansho,
    COUNT(fuseiritsu_flag_fukusho) AS cnt_fuseiritsu_flag_fukusho,
    ROUND(COUNT(fuseiritsu_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_fukusho,
    COUNT(fuseiritsu_flag_wakuren) AS cnt_fuseiritsu_flag_wakuren,
    ROUND(COUNT(fuseiritsu_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_wakuren,
    COUNT(fuseiritsu_flag_umaren) AS cnt_fuseiritsu_flag_umaren,
    ROUND(COUNT(fuseiritsu_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_umaren,
    COUNT(fuseiritsu_flag_wide) AS cnt_fuseiritsu_flag_wide,
    ROUND(COUNT(fuseiritsu_flag_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_wide,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(fuseiritsu_flag_umatan) AS cnt_fuseiritsu_flag_umatan,
    ROUND(COUNT(fuseiritsu_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_umatan,
    COUNT(fuseiritsu_flag_sanrenpuku) AS cnt_fuseiritsu_flag_sanrenpuku,
    ROUND(COUNT(fuseiritsu_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_sanrenpuku,
    COUNT(fuseiritsu_flag_sanrentan) AS cnt_fuseiritsu_flag_sanrentan,
    ROUND(COUNT(fuseiritsu_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) AS rate_fuseiritsu_flag_sanrentan,
    COUNT(tokubarai_flag_tansho) AS cnt_tokubarai_flag_tansho,
    ROUND(COUNT(tokubarai_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_tansho,
    COUNT(tokubarai_flag_fukusho) AS cnt_tokubarai_flag_fukusho,
    ROUND(COUNT(tokubarai_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_fukusho,
    COUNT(tokubarai_flag_wakuren) AS cnt_tokubarai_flag_wakuren,
    ROUND(COUNT(tokubarai_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_wakuren,
    COUNT(tokubarai_flag_umaren) AS cnt_tokubarai_flag_umaren,
    ROUND(COUNT(tokubarai_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_umaren,
    COUNT(tokubarai_flag_wide) AS cnt_tokubarai_flag_wide,
    ROUND(COUNT(tokubarai_flag_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_wide,
    COUNT(yobi_2) AS cnt_yobi_2,
    ROUND(COUNT(yobi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_2,
    COUNT(tokubarai_flag_umatan) AS cnt_tokubarai_flag_umatan,
    ROUND(COUNT(tokubarai_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_umatan,
    COUNT(tokubarai_flag_sanrenpuku) AS cnt_tokubarai_flag_sanrenpuku,
    ROUND(COUNT(tokubarai_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_sanrenpuku,
    COUNT(tokubarai_flag_sanrentan) AS cnt_tokubarai_flag_sanrentan,
    ROUND(COUNT(tokubarai_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokubarai_flag_sanrentan,
    COUNT(henkan_flag_tansho) AS cnt_henkan_flag_tansho,
    ROUND(COUNT(henkan_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_tansho,
    COUNT(henkan_flag_fukusho) AS cnt_henkan_flag_fukusho,
    ROUND(COUNT(henkan_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_fukusho,
    COUNT(henkan_flag_wakuren) AS cnt_henkan_flag_wakuren,
    ROUND(COUNT(henkan_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_wakuren,
    COUNT(henkan_flag_umaren) AS cnt_henkan_flag_umaren,
    ROUND(COUNT(henkan_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_umaren,
    COUNT(henkan_flag_wide) AS cnt_henkan_flag_wide,
    ROUND(COUNT(henkan_flag_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_wide,
    COUNT(yobi_3) AS cnt_yobi_3,
    ROUND(COUNT(yobi_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_3,
    COUNT(henkan_flag_umatan) AS cnt_henkan_flag_umatan,
    ROUND(COUNT(henkan_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_umatan,
    COUNT(henkan_flag_sanrenpuku) AS cnt_henkan_flag_sanrenpuku,
    ROUND(COUNT(henkan_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_sanrenpuku,
    COUNT(henkan_flag_sanrentan) AS cnt_henkan_flag_sanrentan,
    ROUND(COUNT(henkan_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_flag_sanrentan,
    COUNT(henkan_umaban_joho) AS cnt_henkan_umaban_joho,
    ROUND(COUNT(henkan_umaban_joho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_umaban_joho,
    COUNT(henkan_wakuban_joho) AS cnt_henkan_wakuban_joho,
    ROUND(COUNT(henkan_wakuban_joho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_wakuban_joho,
    COUNT(henkan_dowaku_joho) AS cnt_henkan_dowaku_joho,
    ROUND(COUNT(henkan_dowaku_joho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_dowaku_joho,
    COUNT(haraimodoshi_tansho_1a) AS cnt_haraimodoshi_tansho_1a,
    ROUND(COUNT(haraimodoshi_tansho_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_1a,
    COUNT(haraimodoshi_tansho_1b) AS cnt_haraimodoshi_tansho_1b,
    ROUND(COUNT(haraimodoshi_tansho_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_1b,
    COUNT(haraimodoshi_tansho_1c) AS cnt_haraimodoshi_tansho_1c,
    ROUND(COUNT(haraimodoshi_tansho_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_1c,
    COUNT(haraimodoshi_tansho_2a) AS cnt_haraimodoshi_tansho_2a,
    ROUND(COUNT(haraimodoshi_tansho_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_2a,
    COUNT(haraimodoshi_tansho_2b) AS cnt_haraimodoshi_tansho_2b,
    ROUND(COUNT(haraimodoshi_tansho_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_2b,
    COUNT(haraimodoshi_tansho_2c) AS cnt_haraimodoshi_tansho_2c,
    ROUND(COUNT(haraimodoshi_tansho_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_2c,
    COUNT(haraimodoshi_tansho_3a) AS cnt_haraimodoshi_tansho_3a,
    ROUND(COUNT(haraimodoshi_tansho_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_3a,
    COUNT(haraimodoshi_tansho_3b) AS cnt_haraimodoshi_tansho_3b,
    ROUND(COUNT(haraimodoshi_tansho_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_3b,
    COUNT(haraimodoshi_tansho_3c) AS cnt_haraimodoshi_tansho_3c,
    ROUND(COUNT(haraimodoshi_tansho_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho_3c,
    COUNT(haraimodoshi_fukusho_1a) AS cnt_haraimodoshi_fukusho_1a,
    ROUND(COUNT(haraimodoshi_fukusho_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_1a,
    COUNT(haraimodoshi_fukusho_1b) AS cnt_haraimodoshi_fukusho_1b,
    ROUND(COUNT(haraimodoshi_fukusho_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_1b,
    COUNT(haraimodoshi_fukusho_1c) AS cnt_haraimodoshi_fukusho_1c,
    ROUND(COUNT(haraimodoshi_fukusho_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_1c,
    COUNT(haraimodoshi_fukusho_2a) AS cnt_haraimodoshi_fukusho_2a,
    ROUND(COUNT(haraimodoshi_fukusho_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_2a,
    COUNT(haraimodoshi_fukusho_2b) AS cnt_haraimodoshi_fukusho_2b,
    ROUND(COUNT(haraimodoshi_fukusho_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_2b,
    COUNT(haraimodoshi_fukusho_2c) AS cnt_haraimodoshi_fukusho_2c,
    ROUND(COUNT(haraimodoshi_fukusho_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_2c,
    COUNT(haraimodoshi_fukusho_3a) AS cnt_haraimodoshi_fukusho_3a,
    ROUND(COUNT(haraimodoshi_fukusho_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_3a,
    COUNT(haraimodoshi_fukusho_3b) AS cnt_haraimodoshi_fukusho_3b,
    ROUND(COUNT(haraimodoshi_fukusho_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_3b,
    COUNT(haraimodoshi_fukusho_3c) AS cnt_haraimodoshi_fukusho_3c,
    ROUND(COUNT(haraimodoshi_fukusho_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_3c,
    COUNT(haraimodoshi_fukusho_4a) AS cnt_haraimodoshi_fukusho_4a,
    ROUND(COUNT(haraimodoshi_fukusho_4a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_4a,
    COUNT(haraimodoshi_fukusho_4b) AS cnt_haraimodoshi_fukusho_4b,
    ROUND(COUNT(haraimodoshi_fukusho_4b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_4b,
    COUNT(haraimodoshi_fukusho_4c) AS cnt_haraimodoshi_fukusho_4c,
    ROUND(COUNT(haraimodoshi_fukusho_4c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_4c,
    COUNT(haraimodoshi_fukusho_5a) AS cnt_haraimodoshi_fukusho_5a,
    ROUND(COUNT(haraimodoshi_fukusho_5a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_5a,
    COUNT(haraimodoshi_fukusho_5b) AS cnt_haraimodoshi_fukusho_5b,
    ROUND(COUNT(haraimodoshi_fukusho_5b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_5b,
    COUNT(haraimodoshi_fukusho_5c) AS cnt_haraimodoshi_fukusho_5c,
    ROUND(COUNT(haraimodoshi_fukusho_5c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho_5c,
    COUNT(haraimodoshi_wakuren_1a) AS cnt_haraimodoshi_wakuren_1a,
    ROUND(COUNT(haraimodoshi_wakuren_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_1a,
    COUNT(haraimodoshi_wakuren_1b) AS cnt_haraimodoshi_wakuren_1b,
    ROUND(COUNT(haraimodoshi_wakuren_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_1b,
    COUNT(haraimodoshi_wakuren_1c) AS cnt_haraimodoshi_wakuren_1c,
    ROUND(COUNT(haraimodoshi_wakuren_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_1c,
    COUNT(haraimodoshi_wakuren_2a) AS cnt_haraimodoshi_wakuren_2a,
    ROUND(COUNT(haraimodoshi_wakuren_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_2a,
    COUNT(haraimodoshi_wakuren_2b) AS cnt_haraimodoshi_wakuren_2b,
    ROUND(COUNT(haraimodoshi_wakuren_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_2b,
    COUNT(haraimodoshi_wakuren_2c) AS cnt_haraimodoshi_wakuren_2c,
    ROUND(COUNT(haraimodoshi_wakuren_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_2c,
    COUNT(haraimodoshi_wakuren_3a) AS cnt_haraimodoshi_wakuren_3a,
    ROUND(COUNT(haraimodoshi_wakuren_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_3a,
    COUNT(haraimodoshi_wakuren_3b) AS cnt_haraimodoshi_wakuren_3b,
    ROUND(COUNT(haraimodoshi_wakuren_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_3b,
    COUNT(haraimodoshi_wakuren_3c) AS cnt_haraimodoshi_wakuren_3c,
    ROUND(COUNT(haraimodoshi_wakuren_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wakuren_3c,
    COUNT(haraimodoshi_umaren_1a) AS cnt_haraimodoshi_umaren_1a,
    ROUND(COUNT(haraimodoshi_umaren_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_1a,
    COUNT(haraimodoshi_umaren_1b) AS cnt_haraimodoshi_umaren_1b,
    ROUND(COUNT(haraimodoshi_umaren_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_1b,
    COUNT(haraimodoshi_umaren_1c) AS cnt_haraimodoshi_umaren_1c,
    ROUND(COUNT(haraimodoshi_umaren_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_1c,
    COUNT(haraimodoshi_umaren_2a) AS cnt_haraimodoshi_umaren_2a,
    ROUND(COUNT(haraimodoshi_umaren_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_2a,
    COUNT(haraimodoshi_umaren_2b) AS cnt_haraimodoshi_umaren_2b,
    ROUND(COUNT(haraimodoshi_umaren_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_2b,
    COUNT(haraimodoshi_umaren_2c) AS cnt_haraimodoshi_umaren_2c,
    ROUND(COUNT(haraimodoshi_umaren_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_2c,
    COUNT(haraimodoshi_umaren_3a) AS cnt_haraimodoshi_umaren_3a,
    ROUND(COUNT(haraimodoshi_umaren_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_3a,
    COUNT(haraimodoshi_umaren_3b) AS cnt_haraimodoshi_umaren_3b,
    ROUND(COUNT(haraimodoshi_umaren_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_3b,
    COUNT(haraimodoshi_umaren_3c) AS cnt_haraimodoshi_umaren_3c,
    ROUND(COUNT(haraimodoshi_umaren_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umaren_3c,
    COUNT(haraimodoshi_wide_1a) AS cnt_haraimodoshi_wide_1a,
    ROUND(COUNT(haraimodoshi_wide_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_1a,
    COUNT(haraimodoshi_wide_1b) AS cnt_haraimodoshi_wide_1b,
    ROUND(COUNT(haraimodoshi_wide_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_1b,
    COUNT(haraimodoshi_wide_1c) AS cnt_haraimodoshi_wide_1c,
    ROUND(COUNT(haraimodoshi_wide_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_1c,
    COUNT(haraimodoshi_wide_2a) AS cnt_haraimodoshi_wide_2a,
    ROUND(COUNT(haraimodoshi_wide_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_2a,
    COUNT(haraimodoshi_wide_2b) AS cnt_haraimodoshi_wide_2b,
    ROUND(COUNT(haraimodoshi_wide_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_2b,
    COUNT(haraimodoshi_wide_2c) AS cnt_haraimodoshi_wide_2c,
    ROUND(COUNT(haraimodoshi_wide_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_2c,
    COUNT(haraimodoshi_wide_3a) AS cnt_haraimodoshi_wide_3a,
    ROUND(COUNT(haraimodoshi_wide_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_3a,
    COUNT(haraimodoshi_wide_3b) AS cnt_haraimodoshi_wide_3b,
    ROUND(COUNT(haraimodoshi_wide_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_3b,
    COUNT(haraimodoshi_wide_3c) AS cnt_haraimodoshi_wide_3c,
    ROUND(COUNT(haraimodoshi_wide_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_3c,
    COUNT(haraimodoshi_wide_4a) AS cnt_haraimodoshi_wide_4a,
    ROUND(COUNT(haraimodoshi_wide_4a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_4a,
    COUNT(haraimodoshi_wide_4b) AS cnt_haraimodoshi_wide_4b,
    ROUND(COUNT(haraimodoshi_wide_4b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_4b,
    COUNT(haraimodoshi_wide_4c) AS cnt_haraimodoshi_wide_4c,
    ROUND(COUNT(haraimodoshi_wide_4c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_4c,
    COUNT(haraimodoshi_wide_5a) AS cnt_haraimodoshi_wide_5a,
    ROUND(COUNT(haraimodoshi_wide_5a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_5a,
    COUNT(haraimodoshi_wide_5b) AS cnt_haraimodoshi_wide_5b,
    ROUND(COUNT(haraimodoshi_wide_5b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_5b,
    COUNT(haraimodoshi_wide_5c) AS cnt_haraimodoshi_wide_5c,
    ROUND(COUNT(haraimodoshi_wide_5c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_5c,
    COUNT(haraimodoshi_wide_6a) AS cnt_haraimodoshi_wide_6a,
    ROUND(COUNT(haraimodoshi_wide_6a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_6a,
    COUNT(haraimodoshi_wide_6b) AS cnt_haraimodoshi_wide_6b,
    ROUND(COUNT(haraimodoshi_wide_6b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_6b,
    COUNT(haraimodoshi_wide_6c) AS cnt_haraimodoshi_wide_6c,
    ROUND(COUNT(haraimodoshi_wide_6c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_6c,
    COUNT(haraimodoshi_wide_7a) AS cnt_haraimodoshi_wide_7a,
    ROUND(COUNT(haraimodoshi_wide_7a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_7a,
    COUNT(haraimodoshi_wide_7b) AS cnt_haraimodoshi_wide_7b,
    ROUND(COUNT(haraimodoshi_wide_7b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_7b,
    COUNT(haraimodoshi_wide_7c) AS cnt_haraimodoshi_wide_7c,
    ROUND(COUNT(haraimodoshi_wide_7c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_wide_7c,
    COUNT(yobi_4_1a) AS cnt_yobi_4_1a,
    ROUND(COUNT(yobi_4_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_1a,
    COUNT(yobi_4_1b) AS cnt_yobi_4_1b,
    ROUND(COUNT(yobi_4_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_1b,
    COUNT(yobi_4_1c) AS cnt_yobi_4_1c,
    ROUND(COUNT(yobi_4_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_1c,
    COUNT(yobi_4_2a) AS cnt_yobi_4_2a,
    ROUND(COUNT(yobi_4_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_2a,
    COUNT(yobi_4_2b) AS cnt_yobi_4_2b,
    ROUND(COUNT(yobi_4_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_2b,
    COUNT(yobi_4_2c) AS cnt_yobi_4_2c,
    ROUND(COUNT(yobi_4_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_2c,
    COUNT(yobi_4_3a) AS cnt_yobi_4_3a,
    ROUND(COUNT(yobi_4_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_3a,
    COUNT(yobi_4_3b) AS cnt_yobi_4_3b,
    ROUND(COUNT(yobi_4_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_3b,
    COUNT(yobi_4_3c) AS cnt_yobi_4_3c,
    ROUND(COUNT(yobi_4_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4_3c,
    COUNT(haraimodoshi_umatan_1a) AS cnt_haraimodoshi_umatan_1a,
    ROUND(COUNT(haraimodoshi_umatan_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_1a,
    COUNT(haraimodoshi_umatan_1b) AS cnt_haraimodoshi_umatan_1b,
    ROUND(COUNT(haraimodoshi_umatan_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_1b,
    COUNT(haraimodoshi_umatan_1c) AS cnt_haraimodoshi_umatan_1c,
    ROUND(COUNT(haraimodoshi_umatan_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_1c,
    COUNT(haraimodoshi_umatan_2a) AS cnt_haraimodoshi_umatan_2a,
    ROUND(COUNT(haraimodoshi_umatan_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_2a,
    COUNT(haraimodoshi_umatan_2b) AS cnt_haraimodoshi_umatan_2b,
    ROUND(COUNT(haraimodoshi_umatan_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_2b,
    COUNT(haraimodoshi_umatan_2c) AS cnt_haraimodoshi_umatan_2c,
    ROUND(COUNT(haraimodoshi_umatan_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_2c,
    COUNT(haraimodoshi_umatan_3a) AS cnt_haraimodoshi_umatan_3a,
    ROUND(COUNT(haraimodoshi_umatan_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_3a,
    COUNT(haraimodoshi_umatan_3b) AS cnt_haraimodoshi_umatan_3b,
    ROUND(COUNT(haraimodoshi_umatan_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_3b,
    COUNT(haraimodoshi_umatan_3c) AS cnt_haraimodoshi_umatan_3c,
    ROUND(COUNT(haraimodoshi_umatan_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_3c,
    COUNT(haraimodoshi_umatan_4a) AS cnt_haraimodoshi_umatan_4a,
    ROUND(COUNT(haraimodoshi_umatan_4a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_4a,
    COUNT(haraimodoshi_umatan_4b) AS cnt_haraimodoshi_umatan_4b,
    ROUND(COUNT(haraimodoshi_umatan_4b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_4b,
    COUNT(haraimodoshi_umatan_4c) AS cnt_haraimodoshi_umatan_4c,
    ROUND(COUNT(haraimodoshi_umatan_4c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_4c,
    COUNT(haraimodoshi_umatan_5a) AS cnt_haraimodoshi_umatan_5a,
    ROUND(COUNT(haraimodoshi_umatan_5a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_5a,
    COUNT(haraimodoshi_umatan_5b) AS cnt_haraimodoshi_umatan_5b,
    ROUND(COUNT(haraimodoshi_umatan_5b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_5b,
    COUNT(haraimodoshi_umatan_5c) AS cnt_haraimodoshi_umatan_5c,
    ROUND(COUNT(haraimodoshi_umatan_5c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_5c,
    COUNT(haraimodoshi_umatan_6a) AS cnt_haraimodoshi_umatan_6a,
    ROUND(COUNT(haraimodoshi_umatan_6a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_6a,
    COUNT(haraimodoshi_umatan_6b) AS cnt_haraimodoshi_umatan_6b,
    ROUND(COUNT(haraimodoshi_umatan_6b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_6b,
    COUNT(haraimodoshi_umatan_6c) AS cnt_haraimodoshi_umatan_6c,
    ROUND(COUNT(haraimodoshi_umatan_6c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_umatan_6c,
    COUNT(haraimodoshi_sanrenpuku_1a) AS cnt_haraimodoshi_sanrenpuku_1a,
    ROUND(COUNT(haraimodoshi_sanrenpuku_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_1a,
    COUNT(haraimodoshi_sanrenpuku_1b) AS cnt_haraimodoshi_sanrenpuku_1b,
    ROUND(COUNT(haraimodoshi_sanrenpuku_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_1b,
    COUNT(haraimodoshi_sanrenpuku_1c) AS cnt_haraimodoshi_sanrenpuku_1c,
    ROUND(COUNT(haraimodoshi_sanrenpuku_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_1c,
    COUNT(haraimodoshi_sanrenpuku_2a) AS cnt_haraimodoshi_sanrenpuku_2a,
    ROUND(COUNT(haraimodoshi_sanrenpuku_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_2a,
    COUNT(haraimodoshi_sanrenpuku_2b) AS cnt_haraimodoshi_sanrenpuku_2b,
    ROUND(COUNT(haraimodoshi_sanrenpuku_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_2b,
    COUNT(haraimodoshi_sanrenpuku_2c) AS cnt_haraimodoshi_sanrenpuku_2c,
    ROUND(COUNT(haraimodoshi_sanrenpuku_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_2c,
    COUNT(haraimodoshi_sanrenpuku_3a) AS cnt_haraimodoshi_sanrenpuku_3a,
    ROUND(COUNT(haraimodoshi_sanrenpuku_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_3a,
    COUNT(haraimodoshi_sanrenpuku_3b) AS cnt_haraimodoshi_sanrenpuku_3b,
    ROUND(COUNT(haraimodoshi_sanrenpuku_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_3b,
    COUNT(haraimodoshi_sanrenpuku_3c) AS cnt_haraimodoshi_sanrenpuku_3c,
    ROUND(COUNT(haraimodoshi_sanrenpuku_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrenpuku_3c,
    COUNT(haraimodoshi_sanrentan_1a) AS cnt_haraimodoshi_sanrentan_1a,
    ROUND(COUNT(haraimodoshi_sanrentan_1a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_1a,
    COUNT(haraimodoshi_sanrentan_1b) AS cnt_haraimodoshi_sanrentan_1b,
    ROUND(COUNT(haraimodoshi_sanrentan_1b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_1b,
    COUNT(haraimodoshi_sanrentan_1c) AS cnt_haraimodoshi_sanrentan_1c,
    ROUND(COUNT(haraimodoshi_sanrentan_1c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_1c,
    COUNT(haraimodoshi_sanrentan_2a) AS cnt_haraimodoshi_sanrentan_2a,
    ROUND(COUNT(haraimodoshi_sanrentan_2a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_2a,
    COUNT(haraimodoshi_sanrentan_2b) AS cnt_haraimodoshi_sanrentan_2b,
    ROUND(COUNT(haraimodoshi_sanrentan_2b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_2b,
    COUNT(haraimodoshi_sanrentan_2c) AS cnt_haraimodoshi_sanrentan_2c,
    ROUND(COUNT(haraimodoshi_sanrentan_2c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_2c,
    COUNT(haraimodoshi_sanrentan_3a) AS cnt_haraimodoshi_sanrentan_3a,
    ROUND(COUNT(haraimodoshi_sanrentan_3a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_3a,
    COUNT(haraimodoshi_sanrentan_3b) AS cnt_haraimodoshi_sanrentan_3b,
    ROUND(COUNT(haraimodoshi_sanrentan_3b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_3b,
    COUNT(haraimodoshi_sanrentan_3c) AS cnt_haraimodoshi_sanrentan_3c,
    ROUND(COUNT(haraimodoshi_sanrentan_3c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_3c,
    COUNT(haraimodoshi_sanrentan_4a) AS cnt_haraimodoshi_sanrentan_4a,
    ROUND(COUNT(haraimodoshi_sanrentan_4a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_4a,
    COUNT(haraimodoshi_sanrentan_4b) AS cnt_haraimodoshi_sanrentan_4b,
    ROUND(COUNT(haraimodoshi_sanrentan_4b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_4b,
    COUNT(haraimodoshi_sanrentan_4c) AS cnt_haraimodoshi_sanrentan_4c,
    ROUND(COUNT(haraimodoshi_sanrentan_4c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_4c,
    COUNT(haraimodoshi_sanrentan_5a) AS cnt_haraimodoshi_sanrentan_5a,
    ROUND(COUNT(haraimodoshi_sanrentan_5a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_5a,
    COUNT(haraimodoshi_sanrentan_5b) AS cnt_haraimodoshi_sanrentan_5b,
    ROUND(COUNT(haraimodoshi_sanrentan_5b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_5b,
    COUNT(haraimodoshi_sanrentan_5c) AS cnt_haraimodoshi_sanrentan_5c,
    ROUND(COUNT(haraimodoshi_sanrentan_5c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_5c,
    COUNT(haraimodoshi_sanrentan_6a) AS cnt_haraimodoshi_sanrentan_6a,
    ROUND(COUNT(haraimodoshi_sanrentan_6a)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_6a,
    COUNT(haraimodoshi_sanrentan_6b) AS cnt_haraimodoshi_sanrentan_6b,
    ROUND(COUNT(haraimodoshi_sanrentan_6b)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_6b,
    COUNT(haraimodoshi_sanrentan_6c) AS cnt_haraimodoshi_sanrentan_6c,
    ROUND(COUNT(haraimodoshi_sanrentan_6c)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_sanrentan_6c
FROM jvd_hr
WHERE kaisai_nen BETWEEN '2016' AND '2025'
;