-- 充填率チェック: jrd_cyb (27カラム)
-- 実行時間: 約1-5分

SELECT
    'jrd_cyb' AS table_name,
    COUNT(*) AS total_records,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(race_shikonen) AS cnt_race_shikonen,
    ROUND(COUNT(race_shikonen)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_shikonen,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(umaban) AS cnt_umaban,
    ROUND(COUNT(umaban)::NUMERIC / COUNT(*) * 100, 2) AS rate_umaban,
    COUNT(chokyo_type) AS cnt_chokyo_type,
    ROUND(COUNT(chokyo_type)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_type,
    COUNT(chokyo_corse_shubetsu) AS cnt_chokyo_corse_shubetsu,
    ROUND(COUNT(chokyo_corse_shubetsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_shubetsu,
    COUNT(chokyo_corse_hanro) AS cnt_chokyo_corse_hanro,
    ROUND(COUNT(chokyo_corse_hanro)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_hanro,
    COUNT(chokyo_corse_wood) AS cnt_chokyo_corse_wood,
    ROUND(COUNT(chokyo_corse_wood)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_wood,
    COUNT(chokyo_corse_dirt) AS cnt_chokyo_corse_dirt,
    ROUND(COUNT(chokyo_corse_dirt)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_dirt,
    COUNT(chokyo_corse_shiba) AS cnt_chokyo_corse_shiba,
    ROUND(COUNT(chokyo_corse_shiba)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_shiba,
    COUNT(chokyo_corse_pool) AS cnt_chokyo_corse_pool,
    ROUND(COUNT(chokyo_corse_pool)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_pool,
    COUNT(chokyo_corse_shogai) AS cnt_chokyo_corse_shogai,
    ROUND(COUNT(chokyo_corse_shogai)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_shogai,
    COUNT(chokyo_corse_polytrack) AS cnt_chokyo_corse_polytrack,
    ROUND(COUNT(chokyo_corse_polytrack)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_corse_polytrack,
    COUNT(chokyo_kyori) AS cnt_chokyo_kyori,
    ROUND(COUNT(chokyo_kyori)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_kyori,
    COUNT(chokyo_juten) AS cnt_chokyo_juten,
    ROUND(COUNT(chokyo_juten)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_juten,
    COUNT(oikiri_shisu) AS cnt_oikiri_shisu,
    ROUND(COUNT(oikiri_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_oikiri_shisu,
    COUNT(shiage_shisu) AS cnt_shiage_shisu,
    ROUND(COUNT(shiage_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiage_shisu,
    COUNT(chokyo_ryo_hyoka) AS cnt_chokyo_ryo_hyoka,
    ROUND(COUNT(chokyo_ryo_hyoka)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_ryo_hyoka,
    COUNT(shiage_shisu_henka) AS cnt_shiage_shisu_henka,
    ROUND(COUNT(shiage_shisu_henka)::NUMERIC / COUNT(*) * 100, 2) AS rate_shiage_shisu_henka,
    COUNT(chokyo_comment) AS cnt_chokyo_comment,
    ROUND(COUNT(chokyo_comment)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_comment,
    COUNT(comment_nengappi) AS cnt_comment_nengappi,
    ROUND(COUNT(comment_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_comment_nengappi,
    COUNT(chokyo_hyoka) AS cnt_chokyo_hyoka,
    ROUND(COUNT(chokyo_hyoka)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_hyoka,
    COUNT(oikiri_shisu_isshumae) AS cnt_oikiri_shisu_isshumae,
    ROUND(COUNT(oikiri_shisu_isshumae)::NUMERIC / COUNT(*) * 100, 2) AS rate_oikiri_shisu_isshumae,
    COUNT(oikiri_corse_isshumae) AS cnt_oikiri_corse_isshumae,
    ROUND(COUNT(oikiri_corse_isshumae)::NUMERIC / COUNT(*) * 100, 2) AS rate_oikiri_corse_isshumae,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1
FROM jrd_cyb
;