-- 充填率チェック: jvd_wh (28カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_wh' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(happyo_tsukihi_jifun) AS cnt_happyo_tsukihi_jifun,
    ROUND(COUNT(happyo_tsukihi_jifun)::NUMERIC / COUNT(*) * 100, 2) AS rate_happyo_tsukihi_jifun,
    COUNT(bataiju_joho_01) AS cnt_bataiju_joho_01,
    ROUND(COUNT(bataiju_joho_01)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_01,
    COUNT(bataiju_joho_02) AS cnt_bataiju_joho_02,
    ROUND(COUNT(bataiju_joho_02)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_02,
    COUNT(bataiju_joho_03) AS cnt_bataiju_joho_03,
    ROUND(COUNT(bataiju_joho_03)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_03,
    COUNT(bataiju_joho_04) AS cnt_bataiju_joho_04,
    ROUND(COUNT(bataiju_joho_04)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_04,
    COUNT(bataiju_joho_05) AS cnt_bataiju_joho_05,
    ROUND(COUNT(bataiju_joho_05)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_05,
    COUNT(bataiju_joho_06) AS cnt_bataiju_joho_06,
    ROUND(COUNT(bataiju_joho_06)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_06,
    COUNT(bataiju_joho_07) AS cnt_bataiju_joho_07,
    ROUND(COUNT(bataiju_joho_07)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_07,
    COUNT(bataiju_joho_08) AS cnt_bataiju_joho_08,
    ROUND(COUNT(bataiju_joho_08)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_08,
    COUNT(bataiju_joho_09) AS cnt_bataiju_joho_09,
    ROUND(COUNT(bataiju_joho_09)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_09,
    COUNT(bataiju_joho_10) AS cnt_bataiju_joho_10,
    ROUND(COUNT(bataiju_joho_10)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_10,
    COUNT(bataiju_joho_11) AS cnt_bataiju_joho_11,
    ROUND(COUNT(bataiju_joho_11)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_11,
    COUNT(bataiju_joho_12) AS cnt_bataiju_joho_12,
    ROUND(COUNT(bataiju_joho_12)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_12,
    COUNT(bataiju_joho_13) AS cnt_bataiju_joho_13,
    ROUND(COUNT(bataiju_joho_13)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_13,
    COUNT(bataiju_joho_14) AS cnt_bataiju_joho_14,
    ROUND(COUNT(bataiju_joho_14)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_14,
    COUNT(bataiju_joho_15) AS cnt_bataiju_joho_15,
    ROUND(COUNT(bataiju_joho_15)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_15,
    COUNT(bataiju_joho_16) AS cnt_bataiju_joho_16,
    ROUND(COUNT(bataiju_joho_16)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_16,
    COUNT(bataiju_joho_17) AS cnt_bataiju_joho_17,
    ROUND(COUNT(bataiju_joho_17)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_17,
    COUNT(bataiju_joho_18) AS cnt_bataiju_joho_18,
    ROUND(COUNT(bataiju_joho_18)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_joho_18
FROM jvd_wh
;