-- 充填率チェック: jrd_sed (80カラム)
-- 実行時間: 約1-5分

SELECT
    'jrd_sed' AS table_name,
    COUNT(*) AS total_records,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(race_shikonen) AS cnt_race_shikonen,
    ROUND(COUNT(race_shikonen)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_shikonen,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(umaban) AS cnt_umaban,
    ROUND(COUNT(umaban)::NUMERIC / COUNT(*) * 100, 2) AS rate_umaban,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(kyori) AS cnt_kyori,
    ROUND(COUNT(kyori)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori,
    COUNT(track_code) AS cnt_track_code,
    ROUND(COUNT(track_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_track_code,
    COUNT(babajotai_code) AS cnt_babajotai_code,
    ROUND(COUNT(babajotai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_babajotai_code,
    COUNT(kyoso_shubetsu_code) AS cnt_kyoso_shubetsu_code,
    ROUND(COUNT(kyoso_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_shubetsu_code,
    COUNT(kyoso_joken_code) AS cnt_kyoso_joken_code,
    ROUND(COUNT(kyoso_joken_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code,
    COUNT(kyoso_kigo_code) AS cnt_kyoso_kigo_code,
    ROUND(COUNT(kyoso_kigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_kigo_code,
    COUNT(juryo_shubetsu_code) AS cnt_juryo_shubetsu_code,
    ROUND(COUNT(juryo_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_juryo_shubetsu_code,
    COUNT(grade_code) AS cnt_grade_code,
    ROUND(COUNT(grade_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_grade_code,
    COUNT(kyosomei) AS cnt_kyosomei,
    ROUND(COUNT(kyosomei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei,
    COUNT(toroku_tosu) AS cnt_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_tosu,
    COUNT(kyosomei_ryakusho_4) AS cnt_kyosomei_ryakusho_4,
    ROUND(COUNT(kyosomei_ryakusho_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_ryakusho_4,
    COUNT(kakutei_chakujun) AS cnt_kakutei_chakujun,
    ROUND(COUNT(kakutei_chakujun)::NUMERIC / COUNT(*) * 100, 2) AS rate_kakutei_chakujun,
    COUNT(ijo_kubun_code) AS cnt_ijo_kubun_code,
    ROUND(COUNT(ijo_kubun_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_ijo_kubun_code,
    COUNT(soha_time) AS cnt_soha_time,
    ROUND(COUNT(soha_time)::NUMERIC / COUNT(*) * 100, 2) AS rate_soha_time,
    COUNT(futan_juryo) AS cnt_futan_juryo,
    ROUND(COUNT(futan_juryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_futan_juryo,
    COUNT(kishumei) AS cnt_kishumei,
    ROUND(COUNT(kishumei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei,
    COUNT(chokyoshimei) AS cnt_chokyoshimei,
    ROUND(COUNT(chokyoshimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei,
    COUNT(tansho_odds) AS cnt_tansho_odds,
    ROUND(COUNT(tansho_odds)::NUMERIC / COUNT(*) * 100, 2) AS rate_tansho_odds,
    COUNT(tansho_ninkijun) AS cnt_tansho_ninkijun,
    ROUND(COUNT(tansho_ninkijun)::NUMERIC / COUNT(*) * 100, 2) AS rate_tansho_ninkijun,
    COUNT(idm) AS cnt_idm,
    ROUND(COUNT(idm)::NUMERIC / COUNT(*) * 100, 2) AS rate_idm,
    COUNT(soten) AS cnt_soten,
    ROUND(COUNT(soten)::NUMERIC / COUNT(*) * 100, 2) AS rate_soten,
    COUNT(babasa) AS cnt_babasa,
    ROUND(COUNT(babasa)::NUMERIC / COUNT(*) * 100, 2) AS rate_babasa,
    COUNT(pace) AS cnt_pace,
    ROUND(COUNT(pace)::NUMERIC / COUNT(*) * 100, 2) AS rate_pace,
    COUNT(deokure) AS cnt_deokure,
    ROUND(COUNT(deokure)::NUMERIC / COUNT(*) * 100, 2) AS rate_deokure,
    COUNT(ichidori) AS cnt_ichidori,
    ROUND(COUNT(ichidori)::NUMERIC / COUNT(*) * 100, 2) AS rate_ichidori,
    COUNT(furi) AS cnt_furi,
    ROUND(COUNT(furi)::NUMERIC / COUNT(*) * 100, 2) AS rate_furi,
    COUNT(furi_1) AS cnt_furi_1,
    ROUND(COUNT(furi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_furi_1,
    COUNT(furi_2) AS cnt_furi_2,
    ROUND(COUNT(furi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_furi_2,
    COUNT(furi_3) AS cnt_furi_3,
    ROUND(COUNT(furi_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_furi_3,
    COUNT(race) AS cnt_race,
    ROUND(COUNT(race)::NUMERIC / COUNT(*) * 100, 2) AS rate_race,
    COUNT(course_dori_code) AS cnt_course_dori_code,
    ROUND(COUNT(course_dori_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_course_dori_code,
    COUNT(joshodo_code) AS cnt_joshodo_code,
    ROUND(COUNT(joshodo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_joshodo_code,
    COUNT(class_code) AS cnt_class_code,
    ROUND(COUNT(class_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_class_code,
    COUNT(batai_code) AS cnt_batai_code,
    ROUND(COUNT(batai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_batai_code,
    COUNT(kehai_code) AS cnt_kehai_code,
    ROUND(COUNT(kehai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kehai_code,
    COUNT(race_pace) AS cnt_race_pace,
    ROUND(COUNT(race_pace)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_pace,
    COUNT(uma_pace) AS cnt_uma_pace,
    ROUND(COUNT(uma_pace)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_pace,
    COUNT(ten_shisu) AS cnt_ten_shisu,
    ROUND(COUNT(ten_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_ten_shisu,
    COUNT(agari_shisu) AS cnt_agari_shisu,
    ROUND(COUNT(agari_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_agari_shisu,
    COUNT(pace_shisu) AS cnt_pace_shisu,
    ROUND(COUNT(pace_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_pace_shisu,
    COUNT(race_p_shisu) AS cnt_race_p_shisu,
    ROUND(COUNT(race_p_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_p_shisu,
    COUNT(aiteuma_joho_1) AS cnt_aiteuma_joho_1,
    ROUND(COUNT(aiteuma_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_aiteuma_joho_1,
    COUNT(zenhan_3f_taimu) AS cnt_zenhan_3f_taimu,
    ROUND(COUNT(zenhan_3f_taimu)::NUMERIC / COUNT(*) * 100, 2) AS rate_zenhan_3f_taimu,
    COUNT(kohan_3f) AS cnt_kohan_3f,
    ROUND(COUNT(kohan_3f)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f,
    COUNT(biko) AS cnt_biko,
    ROUND(COUNT(biko)::NUMERIC / COUNT(*) * 100, 2) AS rate_biko,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(odds_fukusho) AS cnt_odds_fukusho,
    ROUND(COUNT(odds_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_odds_fukusho,
    COUNT(odds_tansho_10am) AS cnt_odds_tansho_10am,
    ROUND(COUNT(odds_tansho_10am)::NUMERIC / COUNT(*) * 100, 2) AS rate_odds_tansho_10am,
    COUNT(odds_fukusho_10am) AS cnt_odds_fukusho_10am,
    ROUND(COUNT(odds_fukusho_10am)::NUMERIC / COUNT(*) * 100, 2) AS rate_odds_fukusho_10am,
    COUNT(corner_1) AS cnt_corner_1,
    ROUND(COUNT(corner_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_1,
    COUNT(corner_2) AS cnt_corner_2,
    ROUND(COUNT(corner_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_2,
    COUNT(corner_3) AS cnt_corner_3,
    ROUND(COUNT(corner_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_3,
    COUNT(corner_4) AS cnt_corner_4,
    ROUND(COUNT(corner_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_corner_4,
    COUNT(zenhan_3f_sento_sa) AS cnt_zenhan_3f_sento_sa,
    ROUND(COUNT(zenhan_3f_sento_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_zenhan_3f_sento_sa,
    COUNT(kohan_3f_sento_sa) AS cnt_kohan_3f_sento_sa,
    ROUND(COUNT(kohan_3f_sento_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f_sento_sa,
    COUNT(kishu_code) AS cnt_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code,
    COUNT(chokyoshi_code) AS cnt_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_code,
    COUNT(bataiju) AS cnt_bataiju,
    ROUND(COUNT(bataiju)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju,
    COUNT(bataiju_zogen) AS cnt_bataiju_zogen,
    ROUND(COUNT(bataiju_zogen)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_zogen,
    COUNT(tenko_code) AS cnt_tenko_code,
    ROUND(COUNT(tenko_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tenko_code,
    COUNT(course_kubun) AS cnt_course_kubun,
    ROUND(COUNT(course_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_course_kubun,
    COUNT(kyakushitsu_code) AS cnt_kyakushitsu_code,
    ROUND(COUNT(kyakushitsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyakushitsu_code,
    COUNT(haraimodoshi_tansho) AS cnt_haraimodoshi_tansho,
    ROUND(COUNT(haraimodoshi_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_tansho,
    COUNT(haraimodoshi_fukusho) AS cnt_haraimodoshi_fukusho,
    ROUND(COUNT(haraimodoshi_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_haraimodoshi_fukusho,
    COUNT(honshokin) AS cnt_honshokin,
    ROUND(COUNT(honshokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_honshokin,
    COUNT(shutoku_shokin) AS cnt_shutoku_shokin,
    ROUND(COUNT(shutoku_shokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_shutoku_shokin,
    COUNT(race_pace_nagare) AS cnt_race_pace_nagare,
    ROUND(COUNT(race_pace_nagare)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_pace_nagare,
    COUNT(uma_pace_nagare) AS cnt_uma_pace_nagare,
    ROUND(COUNT(uma_pace_nagare)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_pace_nagare,
    COUNT(corse_dori_code_corner_4) AS cnt_corse_dori_code_corner_4,
    ROUND(COUNT(corse_dori_code_corner_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_corse_dori_code_corner_4,
    COUNT(hasso_jikoku) AS cnt_hasso_jikoku,
    ROUND(COUNT(hasso_jikoku)::NUMERIC / COUNT(*) * 100, 2) AS rate_hasso_jikoku
FROM jrd_sed
;