-- 充填率チェック: jvd_wc (29カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_wc' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(tracen_kubun) AS cnt_tracen_kubun,
    ROUND(COUNT(tracen_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_tracen_kubun,
    COUNT(chokyo_nengappi) AS cnt_chokyo_nengappi,
    ROUND(COUNT(chokyo_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_nengappi,
    COUNT(chokyo_jikoku) AS cnt_chokyo_jikoku,
    ROUND(COUNT(chokyo_jikoku)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_jikoku,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(course) AS cnt_course,
    ROUND(COUNT(course)::NUMERIC / COUNT(*) * 100, 2) AS rate_course,
    COUNT(babamawari) AS cnt_babamawari,
    ROUND(COUNT(babamawari)::NUMERIC / COUNT(*) * 100, 2) AS rate_babamawari,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(time_gokei_10f) AS cnt_time_gokei_10f,
    ROUND(COUNT(time_gokei_10f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_10f,
    COUNT(lap_time_10f) AS cnt_lap_time_10f,
    ROUND(COUNT(lap_time_10f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_10f,
    COUNT(time_gokei_9f) AS cnt_time_gokei_9f,
    ROUND(COUNT(time_gokei_9f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_9f,
    COUNT(lap_time_9f) AS cnt_lap_time_9f,
    ROUND(COUNT(lap_time_9f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_9f,
    COUNT(time_gokei_8f) AS cnt_time_gokei_8f,
    ROUND(COUNT(time_gokei_8f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_8f,
    COUNT(lap_time_8f) AS cnt_lap_time_8f,
    ROUND(COUNT(lap_time_8f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_8f,
    COUNT(time_gokei_7f) AS cnt_time_gokei_7f,
    ROUND(COUNT(time_gokei_7f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_7f,
    COUNT(lap_time_7f) AS cnt_lap_time_7f,
    ROUND(COUNT(lap_time_7f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_7f,
    COUNT(time_gokei_6f) AS cnt_time_gokei_6f,
    ROUND(COUNT(time_gokei_6f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_6f,
    COUNT(lap_time_6f) AS cnt_lap_time_6f,
    ROUND(COUNT(lap_time_6f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_6f,
    COUNT(time_gokei_5f) AS cnt_time_gokei_5f,
    ROUND(COUNT(time_gokei_5f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_5f,
    COUNT(lap_time_5f) AS cnt_lap_time_5f,
    ROUND(COUNT(lap_time_5f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_5f,
    COUNT(time_gokei_4f) AS cnt_time_gokei_4f,
    ROUND(COUNT(time_gokei_4f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_4f,
    COUNT(lap_time_4f) AS cnt_lap_time_4f,
    ROUND(COUNT(lap_time_4f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_4f,
    COUNT(time_gokei_3f) AS cnt_time_gokei_3f,
    ROUND(COUNT(time_gokei_3f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_3f,
    COUNT(lap_time_3f) AS cnt_lap_time_3f,
    ROUND(COUNT(lap_time_3f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_3f,
    COUNT(time_gokei_2f) AS cnt_time_gokei_2f,
    ROUND(COUNT(time_gokei_2f)::NUMERIC / COUNT(*) * 100, 2) AS rate_time_gokei_2f,
    COUNT(lap_time_2f) AS cnt_lap_time_2f,
    ROUND(COUNT(lap_time_2f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_2f,
    COUNT(lap_time_1f) AS cnt_lap_time_1f,
    ROUND(COUNT(lap_time_1f)::NUMERIC / COUNT(*) * 100, 2) AS rate_lap_time_1f
FROM jvd_wc
;