-- 充填率チェック: jvd_h1 (43カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_h1' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(toroku_tosu) AS cnt_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_tosu,
    COUNT(shusso_tosu) AS cnt_shusso_tosu,
    ROUND(COUNT(shusso_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_shusso_tosu,
    COUNT(hatsubai_flag_tansho) AS cnt_hatsubai_flag_tansho,
    ROUND(COUNT(hatsubai_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_tansho,
    COUNT(hatsubai_flag_fukusho) AS cnt_hatsubai_flag_fukusho,
    ROUND(COUNT(hatsubai_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_fukusho,
    COUNT(hatsubai_flag_wakuren) AS cnt_hatsubai_flag_wakuren,
    ROUND(COUNT(hatsubai_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_wakuren,
    COUNT(hatsubai_flag_umaren) AS cnt_hatsubai_flag_umaren,
    ROUND(COUNT(hatsubai_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_umaren,
    COUNT(hatsubai_flag_wide) AS cnt_hatsubai_flag_wide,
    ROUND(COUNT(hatsubai_flag_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_wide,
    COUNT(hatsubai_flag_umatan) AS cnt_hatsubai_flag_umatan,
    ROUND(COUNT(hatsubai_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_umatan,
    COUNT(hatsubai_flag_sanrenpuku) AS cnt_hatsubai_flag_sanrenpuku,
    ROUND(COUNT(hatsubai_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_hatsubai_flag_sanrenpuku,
    COUNT(fukusho_chakubarai_key) AS cnt_fukusho_chakubarai_key,
    ROUND(COUNT(fukusho_chakubarai_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_fukusho_chakubarai_key,
    COUNT(henkan_umaban_joho) AS cnt_henkan_umaban_joho,
    ROUND(COUNT(henkan_umaban_joho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_umaban_joho,
    COUNT(henkan_wakuban_joho) AS cnt_henkan_wakuban_joho,
    ROUND(COUNT(henkan_wakuban_joho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_wakuban_joho,
    COUNT(henkan_dowaku_joho) AS cnt_henkan_dowaku_joho,
    ROUND(COUNT(henkan_dowaku_joho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_dowaku_joho,
    COUNT(hyosu_tansho) AS cnt_hyosu_tansho,
    ROUND(COUNT(hyosu_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_tansho,
    COUNT(hyosu_fukusho) AS cnt_hyosu_fukusho,
    ROUND(COUNT(hyosu_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_fukusho,
    COUNT(hyosu_wakuren) AS cnt_hyosu_wakuren,
    ROUND(COUNT(hyosu_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_wakuren,
    COUNT(hyosu_umaren) AS cnt_hyosu_umaren,
    ROUND(COUNT(hyosu_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_umaren,
    COUNT(hyosu_wide) AS cnt_hyosu_wide,
    ROUND(COUNT(hyosu_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_wide,
    COUNT(hyosu_umatan) AS cnt_hyosu_umatan,
    ROUND(COUNT(hyosu_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_umatan,
    COUNT(hyosu_sanrenpuku) AS cnt_hyosu_sanrenpuku,
    ROUND(COUNT(hyosu_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_sanrenpuku,
    COUNT(hyosu_gokei_tansho) AS cnt_hyosu_gokei_tansho,
    ROUND(COUNT(hyosu_gokei_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_tansho,
    COUNT(hyosu_gokei_fukusho) AS cnt_hyosu_gokei_fukusho,
    ROUND(COUNT(hyosu_gokei_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_fukusho,
    COUNT(hyosu_gokei_wakuren) AS cnt_hyosu_gokei_wakuren,
    ROUND(COUNT(hyosu_gokei_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_wakuren,
    COUNT(hyosu_gokei_umaren) AS cnt_hyosu_gokei_umaren,
    ROUND(COUNT(hyosu_gokei_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_umaren,
    COUNT(hyosu_gokei_wide) AS cnt_hyosu_gokei_wide,
    ROUND(COUNT(hyosu_gokei_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_wide,
    COUNT(hyosu_gokei_umatan) AS cnt_hyosu_gokei_umatan,
    ROUND(COUNT(hyosu_gokei_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_umatan,
    COUNT(hyosu_gokei_sanrenpuku) AS cnt_hyosu_gokei_sanrenpuku,
    ROUND(COUNT(hyosu_gokei_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_hyosu_gokei_sanrenpuku,
    COUNT(henkan_hyosu_gokei_tansho) AS cnt_henkan_hyosu_gokei_tansho,
    ROUND(COUNT(henkan_hyosu_gokei_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_tansho,
    COUNT(henkan_hyosu_gokei_fukusho) AS cnt_henkan_hyosu_gokei_fukusho,
    ROUND(COUNT(henkan_hyosu_gokei_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_fukusho,
    COUNT(henkan_hyosu_gokei_wakuren) AS cnt_henkan_hyosu_gokei_wakuren,
    ROUND(COUNT(henkan_hyosu_gokei_wakuren)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_wakuren,
    COUNT(henkan_hyosu_gokei_umaren) AS cnt_henkan_hyosu_gokei_umaren,
    ROUND(COUNT(henkan_hyosu_gokei_umaren)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_umaren,
    COUNT(henkan_hyosu_gokei_wide) AS cnt_henkan_hyosu_gokei_wide,
    ROUND(COUNT(henkan_hyosu_gokei_wide)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_wide,
    COUNT(henkan_hyosu_gokei_umatan) AS cnt_henkan_hyosu_gokei_umatan,
    ROUND(COUNT(henkan_hyosu_gokei_umatan)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_umatan,
    COUNT(henkan_hyosu_gokei_sanrenpuku) AS cnt_henkan_hyosu_gokei_sanrenpuku,
    ROUND(COUNT(henkan_hyosu_gokei_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) AS rate_henkan_hyosu_gokei_sanrenpuku
FROM jvd_h1
WHERE kaisai_nen BETWEEN '2016' AND '2025'
;