-- 充填率チェック: jrd_kyi (132カラム)
-- 実行時間: 約1-5分

SELECT
    'jrd_kyi' AS table_name,
    COUNT(*) AS total_records,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(race_shikonen) AS cnt_race_shikonen,
    ROUND(COUNT(race_shikonen)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_shikonen,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(umaban) AS cnt_umaban,
    ROUND(COUNT(umaban)::NUMERIC / COUNT(*) * 100, 2) AS rate_umaban,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(idm) AS cnt_idm,
    ROUND(COUNT(idm)::NUMERIC / COUNT(*) * 100, 2) AS rate_idm,
    COUNT(kishu_shisu) AS cnt_kishu_shisu,
    ROUND(COUNT(kishu_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_shisu,
    COUNT(joho_shisu) AS cnt_joho_shisu,
    ROUND(COUNT(joho_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_joho_shisu,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1,
    COUNT(sogo_shisu) AS cnt_sogo_shisu,
    ROUND(COUNT(sogo_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo_shisu,
    COUNT(kyakushitsu_code) AS cnt_kyakushitsu_code,
    ROUND(COUNT(kyakushitsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyakushitsu_code,
    COUNT(kyori_tekisei_code) AS cnt_kyori_tekisei_code,
    ROUND(COUNT(kyori_tekisei_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori_tekisei_code,
    COUNT(joshodo_code) AS cnt_joshodo_code,
    ROUND(COUNT(joshodo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_joshodo_code,
    COUNT(rotation) AS cnt_rotation,
    ROUND(COUNT(rotation)::NUMERIC / COUNT(*) * 100, 2) AS rate_rotation,
    COUNT(kijun_odds_tansho) AS cnt_kijun_odds_tansho,
    ROUND(COUNT(kijun_odds_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kijun_odds_tansho,
    COUNT(kijun_ninkijun_tansho) AS cnt_kijun_ninkijun_tansho,
    ROUND(COUNT(kijun_ninkijun_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kijun_ninkijun_tansho,
    COUNT(kijun_odds_fukusho) AS cnt_kijun_odds_fukusho,
    ROUND(COUNT(kijun_odds_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kijun_odds_fukusho,
    COUNT(kijun_ninkijun_fukusho) AS cnt_kijun_ninkijun_fukusho,
    ROUND(COUNT(kijun_ninkijun_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kijun_ninkijun_fukusho,
    COUNT(tokutei_joho_1) AS cnt_tokutei_joho_1,
    ROUND(COUNT(tokutei_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokutei_joho_1,
    COUNT(tokutei_joho_2) AS cnt_tokutei_joho_2,
    ROUND(COUNT(tokutei_joho_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokutei_joho_2,
    COUNT(tokutei_joho_3) AS cnt_tokutei_joho_3,
    ROUND(COUNT(tokutei_joho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokutei_joho_3,
    COUNT(tokutei_joho_4) AS cnt_tokutei_joho_4,
    ROUND(COUNT(tokutei_joho_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokutei_joho_4,
    COUNT(tokutei_joho_5) AS cnt_tokutei_joho_5,
    ROUND(COUNT(tokutei_joho_5)::NUMERIC / COUNT(*) * 100, 2) AS rate_tokutei_joho_5,
    COUNT(sogo_joho_1) AS cnt_sogo_joho_1,
    ROUND(COUNT(sogo_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo_joho_1,
    COUNT(sogo_joho_2) AS cnt_sogo_joho_2,
    ROUND(COUNT(sogo_joho_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo_joho_2,
    COUNT(sogo_joho_3) AS cnt_sogo_joho_3,
    ROUND(COUNT(sogo_joho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo_joho_3,
    COUNT(sogo_joho_4) AS cnt_sogo_joho_4,
    ROUND(COUNT(sogo_joho_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo_joho_4,
    COUNT(sogo_joho_5) AS cnt_sogo_joho_5,
    ROUND(COUNT(sogo_joho_5)::NUMERIC / COUNT(*) * 100, 2) AS rate_sogo_joho_5,
    COUNT(ninki_shisu) AS cnt_ninki_shisu,
    ROUND(COUNT(ninki_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_ninki_shisu,
    COUNT(chokyo_shisu) AS cnt_chokyo_shisu,
    ROUND(COUNT(chokyo_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_shisu,
    COUNT(kyusha_shisu) AS cnt_kyusha_shisu,
    ROUND(COUNT(kyusha_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyusha_shisu,
    COUNT(chokyo_yajirushi_code) AS cnt_chokyo_yajirushi_code,
    ROUND(COUNT(chokyo_yajirushi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyo_yajirushi_code,
    COUNT(kyusha_hyoka_code) AS cnt_kyusha_hyoka_code,
    ROUND(COUNT(kyusha_hyoka_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyusha_hyoka_code,
    COUNT(kishu_kitai_rentai_ritsu) AS cnt_kishu_kitai_rentai_ritsu,
    ROUND(COUNT(kishu_kitai_rentai_ritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_kitai_rentai_ritsu,
    COUNT(gekiso_shisu) AS cnt_gekiso_shisu,
    ROUND(COUNT(gekiso_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_gekiso_shisu,
    COUNT(hizume_code) AS cnt_hizume_code,
    ROUND(COUNT(hizume_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_hizume_code,
    COUNT(tekisei_code_omo) AS cnt_tekisei_code_omo,
    ROUND(COUNT(tekisei_code_omo)::NUMERIC / COUNT(*) * 100, 2) AS rate_tekisei_code_omo,
    COUNT(class_code) AS cnt_class_code,
    ROUND(COUNT(class_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_class_code,
    COUNT(yobi_2) AS cnt_yobi_2,
    ROUND(COUNT(yobi_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_2,
    COUNT(blinker_shiyo_kubun) AS cnt_blinker_shiyo_kubun,
    ROUND(COUNT(blinker_shiyo_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_blinker_shiyo_kubun,
    COUNT(kishumei) AS cnt_kishumei,
    ROUND(COUNT(kishumei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishumei,
    COUNT(futan_juryo) AS cnt_futan_juryo,
    ROUND(COUNT(futan_juryo)::NUMERIC / COUNT(*) * 100, 2) AS rate_futan_juryo,
    COUNT(kishu_minarai_code) AS cnt_kishu_minarai_code,
    ROUND(COUNT(kishu_minarai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_minarai_code,
    COUNT(chokyoshimei) AS cnt_chokyoshimei,
    ROUND(COUNT(chokyoshimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei,
    COUNT(chokyoshi_shozoku) AS cnt_chokyoshi_shozoku,
    ROUND(COUNT(chokyoshi_shozoku)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_shozoku,
    COUNT(kako1_kyoso_seiseki_key) AS cnt_kako1_kyoso_seiseki_key,
    ROUND(COUNT(kako1_kyoso_seiseki_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako1_kyoso_seiseki_key,
    COUNT(kako2_kyoso_seiseki_key) AS cnt_kako2_kyoso_seiseki_key,
    ROUND(COUNT(kako2_kyoso_seiseki_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako2_kyoso_seiseki_key,
    COUNT(kako3_kyoso_seiseki_key) AS cnt_kako3_kyoso_seiseki_key,
    ROUND(COUNT(kako3_kyoso_seiseki_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako3_kyoso_seiseki_key,
    COUNT(kako4_kyoso_seiseki_key) AS cnt_kako4_kyoso_seiseki_key,
    ROUND(COUNT(kako4_kyoso_seiseki_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako4_kyoso_seiseki_key,
    COUNT(kako5_kyoso_seiseki_key) AS cnt_kako5_kyoso_seiseki_key,
    ROUND(COUNT(kako5_kyoso_seiseki_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako5_kyoso_seiseki_key,
    COUNT(kako1_race_key) AS cnt_kako1_race_key,
    ROUND(COUNT(kako1_race_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako1_race_key,
    COUNT(kako2_race_key) AS cnt_kako2_race_key,
    ROUND(COUNT(kako2_race_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako2_race_key,
    COUNT(kako3_race_key) AS cnt_kako3_race_key,
    ROUND(COUNT(kako3_race_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako3_race_key,
    COUNT(kako4_race_key) AS cnt_kako4_race_key,
    ROUND(COUNT(kako4_race_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako4_race_key,
    COUNT(kako5_race_key) AS cnt_kako5_race_key,
    ROUND(COUNT(kako5_race_key)::NUMERIC / COUNT(*) * 100, 2) AS rate_kako5_race_key,
    COUNT(wakuban) AS cnt_wakuban,
    ROUND(COUNT(wakuban)::NUMERIC / COUNT(*) * 100, 2) AS rate_wakuban,
    COUNT(yobi_3) AS cnt_yobi_3,
    ROUND(COUNT(yobi_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_3,
    COUNT(shirushi_code_1) AS cnt_shirushi_code_1,
    ROUND(COUNT(shirushi_code_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_1,
    COUNT(shirushi_code_2) AS cnt_shirushi_code_2,
    ROUND(COUNT(shirushi_code_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_2,
    COUNT(shirushi_code_3) AS cnt_shirushi_code_3,
    ROUND(COUNT(shirushi_code_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_3,
    COUNT(shirushi_code_4) AS cnt_shirushi_code_4,
    ROUND(COUNT(shirushi_code_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_4,
    COUNT(shirushi_code_5) AS cnt_shirushi_code_5,
    ROUND(COUNT(shirushi_code_5)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_5,
    COUNT(shirushi_code_6) AS cnt_shirushi_code_6,
    ROUND(COUNT(shirushi_code_6)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_6,
    COUNT(shirushi_code_7) AS cnt_shirushi_code_7,
    ROUND(COUNT(shirushi_code_7)::NUMERIC / COUNT(*) * 100, 2) AS rate_shirushi_code_7,
    COUNT(tekisei_code_shiba) AS cnt_tekisei_code_shiba,
    ROUND(COUNT(tekisei_code_shiba)::NUMERIC / COUNT(*) * 100, 2) AS rate_tekisei_code_shiba,
    COUNT(tekisei_code_dirt) AS cnt_tekisei_code_dirt,
    ROUND(COUNT(tekisei_code_dirt)::NUMERIC / COUNT(*) * 100, 2) AS rate_tekisei_code_dirt,
    COUNT(kishu_code) AS cnt_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_code,
    COUNT(chokyoshi_code) AS cnt_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_code,
    COUNT(yobi_4) AS cnt_yobi_4,
    ROUND(COUNT(yobi_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_4,
    COUNT(kakutoku_shokin_ruikei) AS cnt_kakutoku_shokin_ruikei,
    ROUND(COUNT(kakutoku_shokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kakutoku_shokin_ruikei,
    COUNT(shutoku_shokin_ruikei) AS cnt_shutoku_shokin_ruikei,
    ROUND(COUNT(shutoku_shokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shutoku_shokin_ruikei,
    COUNT(joken_class_code) AS cnt_joken_class_code,
    ROUND(COUNT(joken_class_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_joken_class_code,
    COUNT(ten_shisu) AS cnt_ten_shisu,
    ROUND(COUNT(ten_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_ten_shisu,
    COUNT(pace_shisu) AS cnt_pace_shisu,
    ROUND(COUNT(pace_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_pace_shisu,
    COUNT(agari_shisu) AS cnt_agari_shisu,
    ROUND(COUNT(agari_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_agari_shisu,
    COUNT(ichi_shisu) AS cnt_ichi_shisu,
    ROUND(COUNT(ichi_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_ichi_shisu,
    COUNT(pace_yoso) AS cnt_pace_yoso,
    ROUND(COUNT(pace_yoso)::NUMERIC / COUNT(*) * 100, 2) AS rate_pace_yoso,
    COUNT(dochu_juni) AS cnt_dochu_juni,
    ROUND(COUNT(dochu_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_dochu_juni,
    COUNT(dochu_sa) AS cnt_dochu_sa,
    ROUND(COUNT(dochu_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_dochu_sa,
    COUNT(dochu_uchisoto) AS cnt_dochu_uchisoto,
    ROUND(COUNT(dochu_uchisoto)::NUMERIC / COUNT(*) * 100, 2) AS rate_dochu_uchisoto,
    COUNT(kohan_3f_juni) AS cnt_kohan_3f_juni,
    ROUND(COUNT(kohan_3f_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f_juni,
    COUNT(kohan_3f_sa) AS cnt_kohan_3f_sa,
    ROUND(COUNT(kohan_3f_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f_sa,
    COUNT(kohan_3f_uchisoto) AS cnt_kohan_3f_uchisoto,
    ROUND(COUNT(kohan_3f_uchisoto)::NUMERIC / COUNT(*) * 100, 2) AS rate_kohan_3f_uchisoto,
    COUNT(goal_juni) AS cnt_goal_juni,
    ROUND(COUNT(goal_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_goal_juni,
    COUNT(goal_sa) AS cnt_goal_sa,
    ROUND(COUNT(goal_sa)::NUMERIC / COUNT(*) * 100, 2) AS rate_goal_sa,
    COUNT(goal_uchisoto) AS cnt_goal_uchisoto,
    ROUND(COUNT(goal_uchisoto)::NUMERIC / COUNT(*) * 100, 2) AS rate_goal_uchisoto,
    COUNT(tenkai_kigo_code) AS cnt_tenkai_kigo_code,
    ROUND(COUNT(tenkai_kigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tenkai_kigo_code,
    COUNT(kyori_tekisei_code_2) AS cnt_kyori_tekisei_code_2,
    ROUND(COUNT(kyori_tekisei_code_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori_tekisei_code_2,
    COUNT(bataiju) AS cnt_bataiju,
    ROUND(COUNT(bataiju)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju,
    COUNT(bataiju_zogen) AS cnt_bataiju_zogen,
    ROUND(COUNT(bataiju_zogen)::NUMERIC / COUNT(*) * 100, 2) AS rate_bataiju_zogen,
    COUNT(torikeshi_flag) AS cnt_torikeshi_flag,
    ROUND(COUNT(torikeshi_flag)::NUMERIC / COUNT(*) * 100, 2) AS rate_torikeshi_flag,
    COUNT(seibetsu_code) AS cnt_seibetsu_code,
    ROUND(COUNT(seibetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_seibetsu_code,
    COUNT(banushimei) AS cnt_banushimei,
    ROUND(COUNT(banushimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushimei,
    COUNT(banushikai_code) AS cnt_banushikai_code,
    ROUND(COUNT(banushikai_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_banushikai_code,
    COUNT(umakigo_code) AS cnt_umakigo_code,
    ROUND(COUNT(umakigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_umakigo_code,
    COUNT(gekiso_juni) AS cnt_gekiso_juni,
    ROUND(COUNT(gekiso_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_gekiso_juni,
    COUNT(ls_shisu_juni) AS cnt_ls_shisu_juni,
    ROUND(COUNT(ls_shisu_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_ls_shisu_juni,
    COUNT(ten_shisu_juni) AS cnt_ten_shisu_juni,
    ROUND(COUNT(ten_shisu_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_ten_shisu_juni,
    COUNT(pace_shisu_juni) AS cnt_pace_shisu_juni,
    ROUND(COUNT(pace_shisu_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_pace_shisu_juni,
    COUNT(agari_shisu_juni) AS cnt_agari_shisu_juni,
    ROUND(COUNT(agari_shisu_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_agari_shisu_juni,
    COUNT(ichi_shisu_juni) AS cnt_ichi_shisu_juni,
    ROUND(COUNT(ichi_shisu_juni)::NUMERIC / COUNT(*) * 100, 2) AS rate_ichi_shisu_juni,
    COUNT(kishu_kitai_tansho_ritsu) AS cnt_kishu_kitai_tansho_ritsu,
    ROUND(COUNT(kishu_kitai_tansho_ritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_kitai_tansho_ritsu,
    COUNT(kishu_kitai_sanchakunai_ritsu) AS cnt_kishu_kitai_sanchakunai_ritsu,
    ROUND(COUNT(kishu_kitai_sanchakunai_ritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_kitai_sanchakunai_ritsu,
    COUNT(yuso_kubun) AS cnt_yuso_kubun,
    ROUND(COUNT(yuso_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_yuso_kubun,
    COUNT(soho) AS cnt_soho,
    ROUND(COUNT(soho)::NUMERIC / COUNT(*) * 100, 2) AS rate_soho,
    COUNT(taikei) AS cnt_taikei,
    ROUND(COUNT(taikei)::NUMERIC / COUNT(*) * 100, 2) AS rate_taikei,
    COUNT(taikei_sogo_1) AS cnt_taikei_sogo_1,
    ROUND(COUNT(taikei_sogo_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_taikei_sogo_1,
    COUNT(taikei_sogo_2) AS cnt_taikei_sogo_2,
    ROUND(COUNT(taikei_sogo_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_taikei_sogo_2,
    COUNT(taikei_sogo_3) AS cnt_taikei_sogo_3,
    ROUND(COUNT(taikei_sogo_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_taikei_sogo_3,
    COUNT(uma_tokki_1) AS cnt_uma_tokki_1,
    ROUND(COUNT(uma_tokki_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_tokki_1,
    COUNT(uma_tokki_2) AS cnt_uma_tokki_2,
    ROUND(COUNT(uma_tokki_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_tokki_2,
    COUNT(uma_tokki_3) AS cnt_uma_tokki_3,
    ROUND(COUNT(uma_tokki_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_tokki_3,
    COUNT(uma_start_shisu) AS cnt_uma_start_shisu,
    ROUND(COUNT(uma_start_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_start_shisu,
    COUNT(uma_deokure_ritsu) AS cnt_uma_deokure_ritsu,
    ROUND(COUNT(uma_deokure_ritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_uma_deokure_ritsu,
    COUNT(sanko_zenso) AS cnt_sanko_zenso,
    ROUND(COUNT(sanko_zenso)::NUMERIC / COUNT(*) * 100, 2) AS rate_sanko_zenso,
    COUNT(sanko_zenso_kishu_code) AS cnt_sanko_zenso_kishu_code,
    ROUND(COUNT(sanko_zenso_kishu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_sanko_zenso_kishu_code,
    COUNT(manken_shisu) AS cnt_manken_shisu,
    ROUND(COUNT(manken_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_manken_shisu,
    COUNT(manken_shirushi) AS cnt_manken_shirushi,
    ROUND(COUNT(manken_shirushi)::NUMERIC / COUNT(*) * 100, 2) AS rate_manken_shirushi,
    COUNT(kokyu_flag) AS cnt_kokyu_flag,
    ROUND(COUNT(kokyu_flag)::NUMERIC / COUNT(*) * 100, 2) AS rate_kokyu_flag,
    COUNT(gekiso_type) AS cnt_gekiso_type,
    ROUND(COUNT(gekiso_type)::NUMERIC / COUNT(*) * 100, 2) AS rate_gekiso_type,
    COUNT(kyuyo_riyu_bunrui_code) AS cnt_kyuyo_riyu_bunrui_code,
    ROUND(COUNT(kyuyo_riyu_bunrui_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyuyo_riyu_bunrui_code,
    COUNT(flag) AS cnt_flag,
    ROUND(COUNT(flag)::NUMERIC / COUNT(*) * 100, 2) AS rate_flag,
    COUNT(nyukyu_nansome) AS cnt_nyukyu_nansome,
    ROUND(COUNT(nyukyu_nansome)::NUMERIC / COUNT(*) * 100, 2) AS rate_nyukyu_nansome,
    COUNT(nyukyu_nengappi) AS cnt_nyukyu_nengappi,
    ROUND(COUNT(nyukyu_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_nyukyu_nengappi,
    COUNT(nyukyu_nannichimae) AS cnt_nyukyu_nannichimae,
    ROUND(COUNT(nyukyu_nannichimae)::NUMERIC / COUNT(*) * 100, 2) AS rate_nyukyu_nannichimae,
    COUNT(hobokusaki) AS cnt_hobokusaki,
    ROUND(COUNT(hobokusaki)::NUMERIC / COUNT(*) * 100, 2) AS rate_hobokusaki,
    COUNT(hobokusaki_rank) AS cnt_hobokusaki_rank,
    ROUND(COUNT(hobokusaki_rank)::NUMERIC / COUNT(*) * 100, 2) AS rate_hobokusaki_rank,
    COUNT(kyusha_rank) AS cnt_kyusha_rank,
    ROUND(COUNT(kyusha_rank)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyusha_rank,
    COUNT(yobi_5) AS cnt_yobi_5,
    ROUND(COUNT(yobi_5)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_5
FROM jrd_kyi
;