-- 充填率チェック: jvd_ch (21カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_ch' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(chokyoshi_code) AS cnt_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshi_code,
    COUNT(massho_kubun) AS cnt_massho_kubun,
    ROUND(COUNT(massho_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_massho_kubun,
    COUNT(menkyo_kofu_nengappi) AS cnt_menkyo_kofu_nengappi,
    ROUND(COUNT(menkyo_kofu_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_menkyo_kofu_nengappi,
    COUNT(menkyo_massho_nengappi) AS cnt_menkyo_massho_nengappi,
    ROUND(COUNT(menkyo_massho_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_menkyo_massho_nengappi,
    COUNT(seinengappi) AS cnt_seinengappi,
    ROUND(COUNT(seinengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_seinengappi,
    COUNT(chokyoshimei) AS cnt_chokyoshimei,
    ROUND(COUNT(chokyoshimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei,
    COUNT(chokyoshimei_hankaku_kana) AS cnt_chokyoshimei_hankaku_kana,
    ROUND(COUNT(chokyoshimei_hankaku_kana)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei_hankaku_kana,
    COUNT(chokyoshimei_ryakusho) AS cnt_chokyoshimei_ryakusho,
    ROUND(COUNT(chokyoshimei_ryakusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei_ryakusho,
    COUNT(chokyoshimei_eur) AS cnt_chokyoshimei_eur,
    ROUND(COUNT(chokyoshimei_eur)::NUMERIC / COUNT(*) * 100, 2) AS rate_chokyoshimei_eur,
    COUNT(seibetsu_kubun) AS cnt_seibetsu_kubun,
    ROUND(COUNT(seibetsu_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_seibetsu_kubun,
    COUNT(tozai_shozoku_code) AS cnt_tozai_shozoku_code,
    ROUND(COUNT(tozai_shozoku_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_tozai_shozoku_code,
    COUNT(shotai_chiikimei) AS cnt_shotai_chiikimei,
    ROUND(COUNT(shotai_chiikimei)::NUMERIC / COUNT(*) * 100, 2) AS rate_shotai_chiikimei,
    COUNT(jushoshori_joho_1) AS cnt_jushoshori_joho_1,
    ROUND(COUNT(jushoshori_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_jushoshori_joho_1,
    COUNT(jushoshori_joho_2) AS cnt_jushoshori_joho_2,
    ROUND(COUNT(jushoshori_joho_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_jushoshori_joho_2,
    COUNT(jushoshori_joho_3) AS cnt_jushoshori_joho_3,
    ROUND(COUNT(jushoshori_joho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_jushoshori_joho_3,
    COUNT(seiseki_joho_1) AS cnt_seiseki_joho_1,
    ROUND(COUNT(seiseki_joho_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_1,
    COUNT(seiseki_joho_2) AS cnt_seiseki_joho_2,
    ROUND(COUNT(seiseki_joho_2)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_2,
    COUNT(seiseki_joho_3) AS cnt_seiseki_joho_3,
    ROUND(COUNT(seiseki_joho_3)::NUMERIC / COUNT(*) * 100, 2) AS rate_seiseki_joho_3
FROM jvd_ch
;