-- 充填率チェック: jrd_bac (27カラム)
-- 実行時間: 約1-5分

SELECT
    'jrd_bac' AS table_name,
    COUNT(*) AS total_records,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(race_shikonen) AS cnt_race_shikonen,
    ROUND(COUNT(race_shikonen)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_shikonen,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(hasso_jikoku) AS cnt_hasso_jikoku,
    ROUND(COUNT(hasso_jikoku)::NUMERIC / COUNT(*) * 100, 2) AS rate_hasso_jikoku,
    COUNT(kyori) AS cnt_kyori,
    ROUND(COUNT(kyori)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyori,
    COUNT(track_code) AS cnt_track_code,
    ROUND(COUNT(track_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_track_code,
    COUNT(kyoso_shubetsu_code) AS cnt_kyoso_shubetsu_code,
    ROUND(COUNT(kyoso_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_shubetsu_code,
    COUNT(kyoso_joken_code) AS cnt_kyoso_joken_code,
    ROUND(COUNT(kyoso_joken_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_joken_code,
    COUNT(kyoso_kigo_code) AS cnt_kyoso_kigo_code,
    ROUND(COUNT(kyoso_kigo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyoso_kigo_code,
    COUNT(juryo_shubetsu_code) AS cnt_juryo_shubetsu_code,
    ROUND(COUNT(juryo_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_juryo_shubetsu_code,
    COUNT(grade_code) AS cnt_grade_code,
    ROUND(COUNT(grade_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_grade_code,
    COUNT(kyosomei) AS cnt_kyosomei,
    ROUND(COUNT(kyosomei)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei,
    COUNT(jusho_kaiji) AS cnt_jusho_kaiji,
    ROUND(COUNT(jusho_kaiji)::NUMERIC / COUNT(*) * 100, 2) AS rate_jusho_kaiji,
    COUNT(toroku_tosu) AS cnt_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) AS rate_toroku_tosu,
    COUNT(course_kubun) AS cnt_course_kubun,
    ROUND(COUNT(course_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_course_kubun,
    COUNT(kaisai_kubun) AS cnt_kaisai_kubun,
    ROUND(COUNT(kaisai_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kubun,
    COUNT(kyosomei_ryakusho_4) AS cnt_kyosomei_ryakusho_4,
    ROUND(COUNT(kyosomei_ryakusho_4)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_ryakusho_4,
    COUNT(kyosomei_ryakusho_9) AS cnt_kyosomei_ryakusho_9,
    ROUND(COUNT(kyosomei_ryakusho_9)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyosomei_ryakusho_9,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(honshokin) AS cnt_honshokin,
    ROUND(COUNT(honshokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_honshokin,
    COUNT(fukashokin) AS cnt_fukashokin,
    ROUND(COUNT(fukashokin)::NUMERIC / COUNT(*) * 100, 2) AS rate_fukashokin,
    COUNT(baken_hatsubai_flag) AS cnt_baken_hatsubai_flag,
    ROUND(COUNT(baken_hatsubai_flag)::NUMERIC / COUNT(*) * 100, 2) AS rate_baken_hatsubai_flag,
    COUNT(win5_flag) AS cnt_win5_flag,
    ROUND(COUNT(win5_flag)::NUMERIC / COUNT(*) * 100, 2) AS rate_win5_flag,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1
FROM jrd_bac
;