-- 充填率チェック: jrd_joa (24カラム)
-- 実行時間: 約1-5分

SELECT
    'jrd_joa' AS table_name,
    COUNT(*) AS total_records,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(race_shikonen) AS cnt_race_shikonen,
    ROUND(COUNT(race_shikonen)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_shikonen,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(umaban) AS cnt_umaban,
    ROUND(COUNT(umaban)::NUMERIC / COUNT(*) * 100, 2) AS rate_umaban,
    COUNT(ketto_toroku_bango) AS cnt_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_ketto_toroku_bango,
    COUNT(bamei) AS cnt_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) AS rate_bamei,
    COUNT(kijun_odds_tansho) AS cnt_kijun_odds_tansho,
    ROUND(COUNT(kijun_odds_tansho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kijun_odds_tansho,
    COUNT(kijun_odds_fukusho) AS cnt_kijun_odds_fukusho,
    ROUND(COUNT(kijun_odds_fukusho)::NUMERIC / COUNT(*) * 100, 2) AS rate_kijun_odds_fukusho,
    COUNT(cid_chokyo_soten) AS cnt_cid_chokyo_soten,
    ROUND(COUNT(cid_chokyo_soten)::NUMERIC / COUNT(*) * 100, 2) AS rate_cid_chokyo_soten,
    COUNT(cid_kyusha_soten) AS cnt_cid_kyusha_soten,
    ROUND(COUNT(cid_kyusha_soten)::NUMERIC / COUNT(*) * 100, 2) AS rate_cid_kyusha_soten,
    COUNT(cid_soten) AS cnt_cid_soten,
    ROUND(COUNT(cid_soten)::NUMERIC / COUNT(*) * 100, 2) AS rate_cid_soten,
    COUNT(cid) AS cnt_cid,
    ROUND(COUNT(cid)::NUMERIC / COUNT(*) * 100, 2) AS rate_cid,
    COUNT(ls_shisu) AS cnt_ls_shisu,
    ROUND(COUNT(ls_shisu)::NUMERIC / COUNT(*) * 100, 2) AS rate_ls_shisu,
    COUNT(ls_hyoka) AS cnt_ls_hyoka,
    ROUND(COUNT(ls_hyoka)::NUMERIC / COUNT(*) * 100, 2) AS rate_ls_hyoka,
    COUNT(em) AS cnt_em,
    ROUND(COUNT(em)::NUMERIC / COUNT(*) * 100, 2) AS rate_em,
    COUNT(kyusha_bb_shirushi) AS cnt_kyusha_bb_shirushi,
    ROUND(COUNT(kyusha_bb_shirushi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyusha_bb_shirushi,
    COUNT(kyusha_bb_nijumaru_tansho_kaishuritsu) AS cnt_kyusha_bb_nijumaru_tansho_kaishuritsu,
    ROUND(COUNT(kyusha_bb_nijumaru_tansho_kaishuritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyusha_bb_nijumaru_tansho_kaishuritsu,
    COUNT(kyusha_bb_nijumaru_rentai_ritsu) AS cnt_kyusha_bb_nijumaru_rentai_ritsu,
    ROUND(COUNT(kyusha_bb_nijumaru_rentai_ritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kyusha_bb_nijumaru_rentai_ritsu,
    COUNT(kishu_bb_shirushi) AS cnt_kishu_bb_shirushi,
    ROUND(COUNT(kishu_bb_shirushi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_bb_shirushi,
    COUNT(kishu_bb_nijumaru_tansho_kaishuritsu) AS cnt_kishu_bb_nijumaru_tansho_kaishuritsu,
    ROUND(COUNT(kishu_bb_nijumaru_tansho_kaishuritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_bb_nijumaru_tansho_kaishuritsu,
    COUNT(kishu_bb_nijumaru_rentai_ritsu) AS cnt_kishu_bb_nijumaru_rentai_ritsu,
    ROUND(COUNT(kishu_bb_nijumaru_rentai_ritsu)::NUMERIC / COUNT(*) * 100, 2) AS rate_kishu_bb_nijumaru_rentai_ritsu,
    COUNT(yobi_1) AS cnt_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) AS rate_yobi_1
FROM jrd_joa
;