-- 充填率チェック: jvd_dm (28カラム)
-- 実行時間: 約1-5分

SELECT
    'jvd_dm' AS table_name,
    COUNT(*) AS total_records,
    COUNT(record_id) AS cnt_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) AS rate_record_id,
    COUNT(data_kubun) AS cnt_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_kubun,
    COUNT(data_sakusei_nengappi) AS cnt_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_nengappi,
    COUNT(kaisai_nen) AS cnt_kaisai_nen,
    ROUND(COUNT(kaisai_nen)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nen,
    COUNT(kaisai_tsukihi) AS cnt_kaisai_tsukihi,
    ROUND(COUNT(kaisai_tsukihi)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_tsukihi,
    COUNT(keibajo_code) AS cnt_keibajo_code,
    ROUND(COUNT(keibajo_code)::NUMERIC / COUNT(*) * 100, 2) AS rate_keibajo_code,
    COUNT(kaisai_kai) AS cnt_kaisai_kai,
    ROUND(COUNT(kaisai_kai)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_kai,
    COUNT(kaisai_nichime) AS cnt_kaisai_nichime,
    ROUND(COUNT(kaisai_nichime)::NUMERIC / COUNT(*) * 100, 2) AS rate_kaisai_nichime,
    COUNT(race_bango) AS cnt_race_bango,
    ROUND(COUNT(race_bango)::NUMERIC / COUNT(*) * 100, 2) AS rate_race_bango,
    COUNT(data_sakusei_jifun) AS cnt_data_sakusei_jifun,
    ROUND(COUNT(data_sakusei_jifun)::NUMERIC / COUNT(*) * 100, 2) AS rate_data_sakusei_jifun,
    COUNT(mining_yoso_01) AS cnt_mining_yoso_01,
    ROUND(COUNT(mining_yoso_01)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_01,
    COUNT(mining_yoso_02) AS cnt_mining_yoso_02,
    ROUND(COUNT(mining_yoso_02)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_02,
    COUNT(mining_yoso_03) AS cnt_mining_yoso_03,
    ROUND(COUNT(mining_yoso_03)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_03,
    COUNT(mining_yoso_04) AS cnt_mining_yoso_04,
    ROUND(COUNT(mining_yoso_04)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_04,
    COUNT(mining_yoso_05) AS cnt_mining_yoso_05,
    ROUND(COUNT(mining_yoso_05)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_05,
    COUNT(mining_yoso_06) AS cnt_mining_yoso_06,
    ROUND(COUNT(mining_yoso_06)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_06,
    COUNT(mining_yoso_07) AS cnt_mining_yoso_07,
    ROUND(COUNT(mining_yoso_07)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_07,
    COUNT(mining_yoso_08) AS cnt_mining_yoso_08,
    ROUND(COUNT(mining_yoso_08)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_08,
    COUNT(mining_yoso_09) AS cnt_mining_yoso_09,
    ROUND(COUNT(mining_yoso_09)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_09,
    COUNT(mining_yoso_10) AS cnt_mining_yoso_10,
    ROUND(COUNT(mining_yoso_10)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_10,
    COUNT(mining_yoso_11) AS cnt_mining_yoso_11,
    ROUND(COUNT(mining_yoso_11)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_11,
    COUNT(mining_yoso_12) AS cnt_mining_yoso_12,
    ROUND(COUNT(mining_yoso_12)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_12,
    COUNT(mining_yoso_13) AS cnt_mining_yoso_13,
    ROUND(COUNT(mining_yoso_13)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_13,
    COUNT(mining_yoso_14) AS cnt_mining_yoso_14,
    ROUND(COUNT(mining_yoso_14)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_14,
    COUNT(mining_yoso_15) AS cnt_mining_yoso_15,
    ROUND(COUNT(mining_yoso_15)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_15,
    COUNT(mining_yoso_16) AS cnt_mining_yoso_16,
    ROUND(COUNT(mining_yoso_16)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_16,
    COUNT(mining_yoso_17) AS cnt_mining_yoso_17,
    ROUND(COUNT(mining_yoso_17)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_17,
    COUNT(mining_yoso_18) AS cnt_mining_yoso_18,
    ROUND(COUNT(mining_yoso_18)::NUMERIC / COUNT(*) * 100, 2) AS rate_mining_yoso_18
FROM jvd_dm
WHERE kaisai_nen BETWEEN '2016' AND '2025'
;