-- ============================================================
-- Phase 7-A 優先度S+A 423カラムの充填率確認
-- 作成日: 2026-03-03
-- 対象: jvd_se(57), jvd_ra(48), jvd_hr(151), jvd_ck(100), 
--       jvd_h1(36), jvd_h6(9), jvd_dm(22)
-- ============================================================

-- 【実行方法】
-- 1. pgAdmin4でこのSQLを開く
-- 2. 各テーブルのSQLを個別に実行（Ctrl+Shift+Eで選択実行）
-- 3. 結果をCSVにエクスポート:
--    - jvd_se_fillrate.csv
--    - jvd_ra_fillrate.csv
--    - ... (計7ファイル)
-- 4. 全CSVをアップロード


-- ============================================================
-- JVD_SE (57カラム, 739,040行)
-- ============================================================

SELECT 
    'jvd_se' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(ketto_toroku_bango) as filled_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) as fillrate_ketto_toroku_bango,
    COUNT(bamei) as filled_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_bamei,
    COUNT(umakigo_code) as filled_umakigo_code,
    ROUND(COUNT(umakigo_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_umakigo_code,
    COUNT(hinshu_code) as filled_hinshu_code,
    ROUND(COUNT(hinshu_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hinshu_code,
    COUNT(moshoku_code) as filled_moshoku_code,
    ROUND(COUNT(moshoku_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_moshoku_code,
    COUNT(tozai_shozoku_code) as filled_tozai_shozoku_code,
    ROUND(COUNT(tozai_shozoku_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tozai_shozoku_code,
    COUNT(chokyoshi_code) as filled_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chokyoshi_code,
    COUNT(chokyoshimei_ryakusho) as filled_chokyoshimei_ryakusho,
    ROUND(COUNT(chokyoshimei_ryakusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chokyoshimei_ryakusho,
    COUNT(banushi_code) as filled_banushi_code,
    ROUND(COUNT(banushi_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_banushi_code,
    COUNT(banushimei) as filled_banushimei,
    ROUND(COUNT(banushimei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_banushimei,
    COUNT(fukushoku_hyoji) as filled_fukushoku_hyoji,
    ROUND(COUNT(fukushoku_hyoji)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fukushoku_hyoji,
    COUNT(yobi_1) as filled_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_1,
    COUNT(futan_juryo) as filled_futan_juryo,
    ROUND(COUNT(futan_juryo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_futan_juryo,
    COUNT(futan_juryo_henkomae) as filled_futan_juryo_henkomae,
    ROUND(COUNT(futan_juryo_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_futan_juryo_henkomae,
    COUNT(yobi_2) as filled_yobi_2,
    ROUND(COUNT(yobi_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_2,
    COUNT(kishu_code) as filled_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishu_code,
    COUNT(kishu_code_henkomae) as filled_kishu_code_henkomae,
    ROUND(COUNT(kishu_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishu_code_henkomae,
    COUNT(kishumei_ryakusho_henkomae) as filled_kishumei_ryakusho_henkomae,
    ROUND(COUNT(kishumei_ryakusho_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishumei_ryakusho_henkomae,
    COUNT(kishu_minarai_code) as filled_kishu_minarai_code,
    ROUND(COUNT(kishu_minarai_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishu_minarai_code,
    COUNT(kishu_minarai_code_henkomae) as filled_kishu_minarai_code_henkomae,
    ROUND(COUNT(kishu_minarai_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishu_minarai_code_henkomae,
    COUNT(bataiju) as filled_bataiju,
    ROUND(COUNT(bataiju)::NUMERIC / COUNT(*) * 100, 2) as fillrate_bataiju,
    COUNT(zogen_fugo) as filled_zogen_fugo,
    ROUND(COUNT(zogen_fugo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_zogen_fugo,
    COUNT(ijo_kubun_code) as filled_ijo_kubun_code,
    ROUND(COUNT(ijo_kubun_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_ijo_kubun_code,
    COUNT(nyusen_juni) as filled_nyusen_juni,
    ROUND(COUNT(nyusen_juni)::NUMERIC / COUNT(*) * 100, 2) as fillrate_nyusen_juni,
    COUNT(kakutei_chakujun) as filled_kakutei_chakujun,
    ROUND(COUNT(kakutei_chakujun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kakutei_chakujun,
    COUNT(dochaku_kubun) as filled_dochaku_kubun,
    ROUND(COUNT(dochaku_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dochaku_kubun,
    COUNT(dochaku_tosu) as filled_dochaku_tosu,
    ROUND(COUNT(dochaku_tosu)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dochaku_tosu,
    COUNT(soha_time) as filled_soha_time,
    ROUND(COUNT(soha_time)::NUMERIC / COUNT(*) * 100, 2) as fillrate_soha_time,
    COUNT(chakusa_code_1) as filled_chakusa_code_1,
    ROUND(COUNT(chakusa_code_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chakusa_code_1,
    COUNT(chakusa_code_2) as filled_chakusa_code_2,
    ROUND(COUNT(chakusa_code_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chakusa_code_2,
    COUNT(chakusa_code_3) as filled_chakusa_code_3,
    ROUND(COUNT(chakusa_code_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chakusa_code_3,
    COUNT(corner_1) as filled_corner_1,
    ROUND(COUNT(corner_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_1,
    COUNT(corner_2) as filled_corner_2,
    ROUND(COUNT(corner_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_2,
    COUNT(corner_3) as filled_corner_3,
    ROUND(COUNT(corner_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_3,
    COUNT(corner_4) as filled_corner_4,
    ROUND(COUNT(corner_4)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_4,
    COUNT(tansho_odds) as filled_tansho_odds,
    ROUND(COUNT(tansho_odds)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tansho_odds,
    COUNT(tansho_ninkijun) as filled_tansho_ninkijun,
    ROUND(COUNT(tansho_ninkijun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tansho_ninkijun,
    COUNT(kakutoku_honshokin) as filled_kakutoku_honshokin,
    ROUND(COUNT(kakutoku_honshokin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kakutoku_honshokin,
    COUNT(kakutoku_fukashokin) as filled_kakutoku_fukashokin,
    ROUND(COUNT(kakutoku_fukashokin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kakutoku_fukashokin,
    COUNT(yobi_3) as filled_yobi_3,
    ROUND(COUNT(yobi_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_3,
    COUNT(yobi_4) as filled_yobi_4,
    ROUND(COUNT(yobi_4)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4,
    COUNT(kohan_4f) as filled_kohan_4f,
    ROUND(COUNT(kohan_4f)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kohan_4f,
    COUNT(kohan_3f) as filled_kohan_3f,
    ROUND(COUNT(kohan_3f)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kohan_3f,
    COUNT(aiteuma_joho_1) as filled_aiteuma_joho_1,
    ROUND(COUNT(aiteuma_joho_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_aiteuma_joho_1,
    COUNT(aiteuma_joho_2) as filled_aiteuma_joho_2,
    ROUND(COUNT(aiteuma_joho_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_aiteuma_joho_2,
    COUNT(aiteuma_joho_3) as filled_aiteuma_joho_3,
    ROUND(COUNT(aiteuma_joho_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_aiteuma_joho_3,
    COUNT(time_sa) as filled_time_sa,
    ROUND(COUNT(time_sa)::NUMERIC / COUNT(*) * 100, 2) as fillrate_time_sa,
    COUNT(record_koshin_kubun) as filled_record_koshin_kubun,
    ROUND(COUNT(record_koshin_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_koshin_kubun,
    COUNT(mining_kubun) as filled_mining_kubun,
    ROUND(COUNT(mining_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_kubun,
    COUNT(yoso_soha_time) as filled_yoso_soha_time,
    ROUND(COUNT(yoso_soha_time)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yoso_soha_time,
    COUNT(yoso_gosa_plus) as filled_yoso_gosa_plus,
    ROUND(COUNT(yoso_gosa_plus)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yoso_gosa_plus,
    COUNT(yoso_gosa_minus) as filled_yoso_gosa_minus,
    ROUND(COUNT(yoso_gosa_minus)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yoso_gosa_minus,
    COUNT(yoso_juni) as filled_yoso_juni,
    ROUND(COUNT(yoso_juni)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yoso_juni,
    COUNT(kyakushitsu_hantei) as filled_kyakushitsu_hantei,
    ROUND(COUNT(kyakushitsu_hantei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyakushitsu_hantei
FROM jvd_se
WHERE kaisai_nen BETWEEN '2016' AND '2025';


-- ============================================================
-- JVD_RA (48カラム, 59,851行)
-- ============================================================

SELECT 
    'jvd_ra' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(yobi_code) as filled_yobi_code,
    ROUND(COUNT(yobi_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_code,
    COUNT(tokubetsu_kyoso_bango) as filled_tokubetsu_kyoso_bango,
    ROUND(COUNT(tokubetsu_kyoso_bango)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubetsu_kyoso_bango,
    COUNT(kyosomei_hondai) as filled_kyosomei_hondai,
    ROUND(COUNT(kyosomei_hondai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_hondai,
    COUNT(kyosomei_fukudai) as filled_kyosomei_fukudai,
    ROUND(COUNT(kyosomei_fukudai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_fukudai,
    COUNT(kyosomei_kakkonai) as filled_kyosomei_kakkonai,
    ROUND(COUNT(kyosomei_kakkonai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_kakkonai,
    COUNT(kyosomei_hondai_eur) as filled_kyosomei_hondai_eur,
    ROUND(COUNT(kyosomei_hondai_eur)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_hondai_eur,
    COUNT(kyosomei_fukudai_eur) as filled_kyosomei_fukudai_eur,
    ROUND(COUNT(kyosomei_fukudai_eur)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_fukudai_eur,
    COUNT(kyosomei_kakkonai_eur) as filled_kyosomei_kakkonai_eur,
    ROUND(COUNT(kyosomei_kakkonai_eur)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_kakkonai_eur,
    COUNT(kyosomei_ryakusho_10) as filled_kyosomei_ryakusho_10,
    ROUND(COUNT(kyosomei_ryakusho_10)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_ryakusho_10,
    COUNT(kyosomei_ryakusho_6) as filled_kyosomei_ryakusho_6,
    ROUND(COUNT(kyosomei_ryakusho_6)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_ryakusho_6,
    COUNT(kyosomei_ryakusho_3) as filled_kyosomei_ryakusho_3,
    ROUND(COUNT(kyosomei_ryakusho_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_ryakusho_3,
    COUNT(kyosomei_kubun) as filled_kyosomei_kubun,
    ROUND(COUNT(kyosomei_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyosomei_kubun,
    COUNT(jusho_kaiji) as filled_jusho_kaiji,
    ROUND(COUNT(jusho_kaiji)::NUMERIC / COUNT(*) * 100, 2) as fillrate_jusho_kaiji,
    COUNT(grade_code_henkomae) as filled_grade_code_henkomae,
    ROUND(COUNT(grade_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_grade_code_henkomae,
    COUNT(kyoso_shubetsu_code) as filled_kyoso_shubetsu_code,
    ROUND(COUNT(kyoso_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_shubetsu_code,
    COUNT(kyoso_kigo_code) as filled_kyoso_kigo_code,
    ROUND(COUNT(kyoso_kigo_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_kigo_code,
    COUNT(juryo_shubetsu_code) as filled_juryo_shubetsu_code,
    ROUND(COUNT(juryo_shubetsu_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_juryo_shubetsu_code,
    COUNT(kyoso_joken_code_2sai) as filled_kyoso_joken_code_2sai,
    ROUND(COUNT(kyoso_joken_code_2sai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_joken_code_2sai,
    COUNT(kyoso_joken_code_3sai) as filled_kyoso_joken_code_3sai,
    ROUND(COUNT(kyoso_joken_code_3sai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_joken_code_3sai,
    COUNT(kyoso_joken_code_4sai) as filled_kyoso_joken_code_4sai,
    ROUND(COUNT(kyoso_joken_code_4sai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_joken_code_4sai,
    COUNT(kyoso_joken_code_5sai_ijo) as filled_kyoso_joken_code_5sai_ijo,
    ROUND(COUNT(kyoso_joken_code_5sai_ijo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_joken_code_5sai_ijo,
    COUNT(kyoso_joken_code) as filled_kyoso_joken_code,
    ROUND(COUNT(kyoso_joken_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_joken_code,
    COUNT(kyoso_joken_meisho) as filled_kyoso_joken_meisho,
    ROUND(COUNT(kyoso_joken_meisho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyoso_joken_meisho,
    COUNT(kyori_henkomae) as filled_kyori_henkomae,
    ROUND(COUNT(kyori_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyori_henkomae,
    COUNT(track_code_henkomae) as filled_track_code_henkomae,
    ROUND(COUNT(track_code_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_track_code_henkomae,
    COUNT(course_kubun) as filled_course_kubun,
    ROUND(COUNT(course_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_course_kubun,
    COUNT(course_kubun_henkomae) as filled_course_kubun_henkomae,
    ROUND(COUNT(course_kubun_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_course_kubun_henkomae,
    COUNT(honshokin) as filled_honshokin,
    ROUND(COUNT(honshokin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_honshokin,
    COUNT(honshokin_henkomae) as filled_honshokin_henkomae,
    ROUND(COUNT(honshokin_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_honshokin_henkomae,
    COUNT(fukashokin) as filled_fukashokin,
    ROUND(COUNT(fukashokin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fukashokin,
    COUNT(fukashokin_henkomae) as filled_fukashokin_henkomae,
    ROUND(COUNT(fukashokin_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fukashokin_henkomae,
    COUNT(hasso_jikoku_henkomae) as filled_hasso_jikoku_henkomae,
    ROUND(COUNT(hasso_jikoku_henkomae)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hasso_jikoku_henkomae,
    COUNT(toroku_tosu) as filled_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) as fillrate_toroku_tosu,
    COUNT(nyusen_tosu) as filled_nyusen_tosu,
    ROUND(COUNT(nyusen_tosu)::NUMERIC / COUNT(*) * 100, 2) as fillrate_nyusen_tosu,
    COUNT(lap_time) as filled_lap_time,
    ROUND(COUNT(lap_time)::NUMERIC / COUNT(*) * 100, 2) as fillrate_lap_time,
    COUNT(shogai_mile_time) as filled_shogai_mile_time,
    ROUND(COUNT(shogai_mile_time)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_mile_time,
    COUNT(zenhan_3f) as filled_zenhan_3f,
    ROUND(COUNT(zenhan_3f)::NUMERIC / COUNT(*) * 100, 2) as fillrate_zenhan_3f,
    COUNT(zenhan_4f) as filled_zenhan_4f,
    ROUND(COUNT(zenhan_4f)::NUMERIC / COUNT(*) * 100, 2) as fillrate_zenhan_4f,
    COUNT(kohan_3f) as filled_kohan_3f,
    ROUND(COUNT(kohan_3f)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kohan_3f,
    COUNT(kohan_4f) as filled_kohan_4f,
    ROUND(COUNT(kohan_4f)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kohan_4f,
    COUNT(corner_tsuka_juni_1) as filled_corner_tsuka_juni_1,
    ROUND(COUNT(corner_tsuka_juni_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_tsuka_juni_1,
    COUNT(corner_tsuka_juni_2) as filled_corner_tsuka_juni_2,
    ROUND(COUNT(corner_tsuka_juni_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_tsuka_juni_2,
    COUNT(corner_tsuka_juni_3) as filled_corner_tsuka_juni_3,
    ROUND(COUNT(corner_tsuka_juni_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_tsuka_juni_3,
    COUNT(corner_tsuka_juni_4) as filled_corner_tsuka_juni_4,
    ROUND(COUNT(corner_tsuka_juni_4)::NUMERIC / COUNT(*) * 100, 2) as fillrate_corner_tsuka_juni_4,
    COUNT(record_koshin_kubun) as filled_record_koshin_kubun,
    ROUND(COUNT(record_koshin_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_koshin_kubun
FROM jvd_ra
WHERE kaisai_nen BETWEEN '2016' AND '2025';


-- ============================================================
-- JVD_HR (151カラム, 34,548行)
-- ============================================================

SELECT 
    'jvd_hr' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(toroku_tosu) as filled_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) as fillrate_toroku_tosu,
    COUNT(fuseiritsu_flag_tansho) as filled_fuseiritsu_flag_tansho,
    ROUND(COUNT(fuseiritsu_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_tansho,
    COUNT(fuseiritsu_flag_fukusho) as filled_fuseiritsu_flag_fukusho,
    ROUND(COUNT(fuseiritsu_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_fukusho,
    COUNT(fuseiritsu_flag_wakuren) as filled_fuseiritsu_flag_wakuren,
    ROUND(COUNT(fuseiritsu_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_wakuren,
    COUNT(fuseiritsu_flag_umaren) as filled_fuseiritsu_flag_umaren,
    ROUND(COUNT(fuseiritsu_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_umaren,
    COUNT(fuseiritsu_flag_wide) as filled_fuseiritsu_flag_wide,
    ROUND(COUNT(fuseiritsu_flag_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_wide,
    COUNT(yobi_1) as filled_yobi_1,
    ROUND(COUNT(yobi_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_1,
    COUNT(fuseiritsu_flag_umatan) as filled_fuseiritsu_flag_umatan,
    ROUND(COUNT(fuseiritsu_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_umatan,
    COUNT(fuseiritsu_flag_sanrenpuku) as filled_fuseiritsu_flag_sanrenpuku,
    ROUND(COUNT(fuseiritsu_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_sanrenpuku,
    COUNT(fuseiritsu_flag_sanrentan) as filled_fuseiritsu_flag_sanrentan,
    ROUND(COUNT(fuseiritsu_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fuseiritsu_flag_sanrentan,
    COUNT(tokubarai_flag_tansho) as filled_tokubarai_flag_tansho,
    ROUND(COUNT(tokubarai_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_tansho,
    COUNT(tokubarai_flag_fukusho) as filled_tokubarai_flag_fukusho,
    ROUND(COUNT(tokubarai_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_fukusho,
    COUNT(tokubarai_flag_wakuren) as filled_tokubarai_flag_wakuren,
    ROUND(COUNT(tokubarai_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_wakuren,
    COUNT(tokubarai_flag_umaren) as filled_tokubarai_flag_umaren,
    ROUND(COUNT(tokubarai_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_umaren,
    COUNT(tokubarai_flag_wide) as filled_tokubarai_flag_wide,
    ROUND(COUNT(tokubarai_flag_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_wide,
    COUNT(yobi_2) as filled_yobi_2,
    ROUND(COUNT(yobi_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_2,
    COUNT(tokubarai_flag_umatan) as filled_tokubarai_flag_umatan,
    ROUND(COUNT(tokubarai_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_umatan,
    COUNT(tokubarai_flag_sanrenpuku) as filled_tokubarai_flag_sanrenpuku,
    ROUND(COUNT(tokubarai_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_sanrenpuku,
    COUNT(tokubarai_flag_sanrentan) as filled_tokubarai_flag_sanrentan,
    ROUND(COUNT(tokubarai_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_tokubarai_flag_sanrentan,
    COUNT(henkan_flag_tansho) as filled_henkan_flag_tansho,
    ROUND(COUNT(henkan_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_tansho,
    COUNT(henkan_flag_fukusho) as filled_henkan_flag_fukusho,
    ROUND(COUNT(henkan_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_fukusho,
    COUNT(henkan_flag_wakuren) as filled_henkan_flag_wakuren,
    ROUND(COUNT(henkan_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_wakuren,
    COUNT(henkan_flag_umaren) as filled_henkan_flag_umaren,
    ROUND(COUNT(henkan_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_umaren,
    COUNT(henkan_flag_wide) as filled_henkan_flag_wide,
    ROUND(COUNT(henkan_flag_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_wide,
    COUNT(yobi_3) as filled_yobi_3,
    ROUND(COUNT(yobi_3)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_3,
    COUNT(henkan_flag_umatan) as filled_henkan_flag_umatan,
    ROUND(COUNT(henkan_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_umatan,
    COUNT(henkan_flag_sanrenpuku) as filled_henkan_flag_sanrenpuku,
    ROUND(COUNT(henkan_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_sanrenpuku,
    COUNT(henkan_flag_sanrentan) as filled_henkan_flag_sanrentan,
    ROUND(COUNT(henkan_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_flag_sanrentan,
    COUNT(henkan_umaban_joho) as filled_henkan_umaban_joho,
    ROUND(COUNT(henkan_umaban_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_umaban_joho,
    COUNT(henkan_wakuban_joho) as filled_henkan_wakuban_joho,
    ROUND(COUNT(henkan_wakuban_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_wakuban_joho,
    COUNT(henkan_dowaku_joho) as filled_henkan_dowaku_joho,
    ROUND(COUNT(henkan_dowaku_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_dowaku_joho,
    COUNT(haraimodoshi_tansho_1a) as filled_haraimodoshi_tansho_1a,
    ROUND(COUNT(haraimodoshi_tansho_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_1a,
    COUNT(haraimodoshi_tansho_1b) as filled_haraimodoshi_tansho_1b,
    ROUND(COUNT(haraimodoshi_tansho_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_1b,
    COUNT(haraimodoshi_tansho_1c) as filled_haraimodoshi_tansho_1c,
    ROUND(COUNT(haraimodoshi_tansho_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_1c,
    COUNT(haraimodoshi_tansho_2a) as filled_haraimodoshi_tansho_2a,
    ROUND(COUNT(haraimodoshi_tansho_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_2a,
    COUNT(haraimodoshi_tansho_2b) as filled_haraimodoshi_tansho_2b,
    ROUND(COUNT(haraimodoshi_tansho_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_2b,
    COUNT(haraimodoshi_tansho_2c) as filled_haraimodoshi_tansho_2c,
    ROUND(COUNT(haraimodoshi_tansho_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_2c,
    COUNT(haraimodoshi_tansho_3a) as filled_haraimodoshi_tansho_3a,
    ROUND(COUNT(haraimodoshi_tansho_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_3a,
    COUNT(haraimodoshi_tansho_3b) as filled_haraimodoshi_tansho_3b,
    ROUND(COUNT(haraimodoshi_tansho_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_3b,
    COUNT(haraimodoshi_tansho_3c) as filled_haraimodoshi_tansho_3c,
    ROUND(COUNT(haraimodoshi_tansho_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_tansho_3c,
    COUNT(haraimodoshi_fukusho_1a) as filled_haraimodoshi_fukusho_1a,
    ROUND(COUNT(haraimodoshi_fukusho_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_1a,
    COUNT(haraimodoshi_fukusho_1b) as filled_haraimodoshi_fukusho_1b,
    ROUND(COUNT(haraimodoshi_fukusho_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_1b,
    COUNT(haraimodoshi_fukusho_1c) as filled_haraimodoshi_fukusho_1c,
    ROUND(COUNT(haraimodoshi_fukusho_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_1c,
    COUNT(haraimodoshi_fukusho_2a) as filled_haraimodoshi_fukusho_2a,
    ROUND(COUNT(haraimodoshi_fukusho_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_2a,
    COUNT(haraimodoshi_fukusho_2b) as filled_haraimodoshi_fukusho_2b,
    ROUND(COUNT(haraimodoshi_fukusho_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_2b,
    COUNT(haraimodoshi_fukusho_2c) as filled_haraimodoshi_fukusho_2c,
    ROUND(COUNT(haraimodoshi_fukusho_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_2c,
    COUNT(haraimodoshi_fukusho_3a) as filled_haraimodoshi_fukusho_3a,
    ROUND(COUNT(haraimodoshi_fukusho_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_3a,
    COUNT(haraimodoshi_fukusho_3b) as filled_haraimodoshi_fukusho_3b,
    ROUND(COUNT(haraimodoshi_fukusho_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_3b,
    COUNT(haraimodoshi_fukusho_3c) as filled_haraimodoshi_fukusho_3c,
    ROUND(COUNT(haraimodoshi_fukusho_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_3c,
    COUNT(haraimodoshi_fukusho_4a) as filled_haraimodoshi_fukusho_4a,
    ROUND(COUNT(haraimodoshi_fukusho_4a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_4a,
    COUNT(haraimodoshi_fukusho_4b) as filled_haraimodoshi_fukusho_4b,
    ROUND(COUNT(haraimodoshi_fukusho_4b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_4b,
    COUNT(haraimodoshi_fukusho_4c) as filled_haraimodoshi_fukusho_4c,
    ROUND(COUNT(haraimodoshi_fukusho_4c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_4c,
    COUNT(haraimodoshi_fukusho_5a) as filled_haraimodoshi_fukusho_5a,
    ROUND(COUNT(haraimodoshi_fukusho_5a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_5a,
    COUNT(haraimodoshi_fukusho_5b) as filled_haraimodoshi_fukusho_5b,
    ROUND(COUNT(haraimodoshi_fukusho_5b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_5b,
    COUNT(haraimodoshi_fukusho_5c) as filled_haraimodoshi_fukusho_5c,
    ROUND(COUNT(haraimodoshi_fukusho_5c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_fukusho_5c,
    COUNT(haraimodoshi_wakuren_1a) as filled_haraimodoshi_wakuren_1a,
    ROUND(COUNT(haraimodoshi_wakuren_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_1a,
    COUNT(haraimodoshi_wakuren_1b) as filled_haraimodoshi_wakuren_1b,
    ROUND(COUNT(haraimodoshi_wakuren_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_1b,
    COUNT(haraimodoshi_wakuren_1c) as filled_haraimodoshi_wakuren_1c,
    ROUND(COUNT(haraimodoshi_wakuren_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_1c,
    COUNT(haraimodoshi_wakuren_2a) as filled_haraimodoshi_wakuren_2a,
    ROUND(COUNT(haraimodoshi_wakuren_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_2a,
    COUNT(haraimodoshi_wakuren_2b) as filled_haraimodoshi_wakuren_2b,
    ROUND(COUNT(haraimodoshi_wakuren_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_2b,
    COUNT(haraimodoshi_wakuren_2c) as filled_haraimodoshi_wakuren_2c,
    ROUND(COUNT(haraimodoshi_wakuren_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_2c,
    COUNT(haraimodoshi_wakuren_3a) as filled_haraimodoshi_wakuren_3a,
    ROUND(COUNT(haraimodoshi_wakuren_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_3a,
    COUNT(haraimodoshi_wakuren_3b) as filled_haraimodoshi_wakuren_3b,
    ROUND(COUNT(haraimodoshi_wakuren_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_3b,
    COUNT(haraimodoshi_wakuren_3c) as filled_haraimodoshi_wakuren_3c,
    ROUND(COUNT(haraimodoshi_wakuren_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wakuren_3c,
    COUNT(haraimodoshi_umaren_1a) as filled_haraimodoshi_umaren_1a,
    ROUND(COUNT(haraimodoshi_umaren_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_1a,
    COUNT(haraimodoshi_umaren_1b) as filled_haraimodoshi_umaren_1b,
    ROUND(COUNT(haraimodoshi_umaren_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_1b,
    COUNT(haraimodoshi_umaren_1c) as filled_haraimodoshi_umaren_1c,
    ROUND(COUNT(haraimodoshi_umaren_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_1c,
    COUNT(haraimodoshi_umaren_2a) as filled_haraimodoshi_umaren_2a,
    ROUND(COUNT(haraimodoshi_umaren_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_2a,
    COUNT(haraimodoshi_umaren_2b) as filled_haraimodoshi_umaren_2b,
    ROUND(COUNT(haraimodoshi_umaren_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_2b,
    COUNT(haraimodoshi_umaren_2c) as filled_haraimodoshi_umaren_2c,
    ROUND(COUNT(haraimodoshi_umaren_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_2c,
    COUNT(haraimodoshi_umaren_3a) as filled_haraimodoshi_umaren_3a,
    ROUND(COUNT(haraimodoshi_umaren_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_3a,
    COUNT(haraimodoshi_umaren_3b) as filled_haraimodoshi_umaren_3b,
    ROUND(COUNT(haraimodoshi_umaren_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_3b,
    COUNT(haraimodoshi_umaren_3c) as filled_haraimodoshi_umaren_3c,
    ROUND(COUNT(haraimodoshi_umaren_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umaren_3c,
    COUNT(haraimodoshi_wide_1a) as filled_haraimodoshi_wide_1a,
    ROUND(COUNT(haraimodoshi_wide_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_1a,
    COUNT(haraimodoshi_wide_1b) as filled_haraimodoshi_wide_1b,
    ROUND(COUNT(haraimodoshi_wide_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_1b,
    COUNT(haraimodoshi_wide_1c) as filled_haraimodoshi_wide_1c,
    ROUND(COUNT(haraimodoshi_wide_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_1c,
    COUNT(haraimodoshi_wide_2a) as filled_haraimodoshi_wide_2a,
    ROUND(COUNT(haraimodoshi_wide_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_2a,
    COUNT(haraimodoshi_wide_2b) as filled_haraimodoshi_wide_2b,
    ROUND(COUNT(haraimodoshi_wide_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_2b,
    COUNT(haraimodoshi_wide_2c) as filled_haraimodoshi_wide_2c,
    ROUND(COUNT(haraimodoshi_wide_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_2c,
    COUNT(haraimodoshi_wide_3a) as filled_haraimodoshi_wide_3a,
    ROUND(COUNT(haraimodoshi_wide_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_3a,
    COUNT(haraimodoshi_wide_3b) as filled_haraimodoshi_wide_3b,
    ROUND(COUNT(haraimodoshi_wide_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_3b,
    COUNT(haraimodoshi_wide_3c) as filled_haraimodoshi_wide_3c,
    ROUND(COUNT(haraimodoshi_wide_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_3c,
    COUNT(haraimodoshi_wide_4a) as filled_haraimodoshi_wide_4a,
    ROUND(COUNT(haraimodoshi_wide_4a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_4a,
    COUNT(haraimodoshi_wide_4b) as filled_haraimodoshi_wide_4b,
    ROUND(COUNT(haraimodoshi_wide_4b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_4b,
    COUNT(haraimodoshi_wide_4c) as filled_haraimodoshi_wide_4c,
    ROUND(COUNT(haraimodoshi_wide_4c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_4c,
    COUNT(haraimodoshi_wide_5a) as filled_haraimodoshi_wide_5a,
    ROUND(COUNT(haraimodoshi_wide_5a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_5a,
    COUNT(haraimodoshi_wide_5b) as filled_haraimodoshi_wide_5b,
    ROUND(COUNT(haraimodoshi_wide_5b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_5b,
    COUNT(haraimodoshi_wide_5c) as filled_haraimodoshi_wide_5c,
    ROUND(COUNT(haraimodoshi_wide_5c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_5c,
    COUNT(haraimodoshi_wide_6a) as filled_haraimodoshi_wide_6a,
    ROUND(COUNT(haraimodoshi_wide_6a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_6a,
    COUNT(haraimodoshi_wide_6b) as filled_haraimodoshi_wide_6b,
    ROUND(COUNT(haraimodoshi_wide_6b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_6b,
    COUNT(haraimodoshi_wide_6c) as filled_haraimodoshi_wide_6c,
    ROUND(COUNT(haraimodoshi_wide_6c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_6c,
    COUNT(haraimodoshi_wide_7a) as filled_haraimodoshi_wide_7a,
    ROUND(COUNT(haraimodoshi_wide_7a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_7a,
    COUNT(haraimodoshi_wide_7b) as filled_haraimodoshi_wide_7b,
    ROUND(COUNT(haraimodoshi_wide_7b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_7b,
    COUNT(haraimodoshi_wide_7c) as filled_haraimodoshi_wide_7c,
    ROUND(COUNT(haraimodoshi_wide_7c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_wide_7c,
    COUNT(yobi_4_1a) as filled_yobi_4_1a,
    ROUND(COUNT(yobi_4_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_1a,
    COUNT(yobi_4_1b) as filled_yobi_4_1b,
    ROUND(COUNT(yobi_4_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_1b,
    COUNT(yobi_4_1c) as filled_yobi_4_1c,
    ROUND(COUNT(yobi_4_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_1c,
    COUNT(yobi_4_2a) as filled_yobi_4_2a,
    ROUND(COUNT(yobi_4_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_2a,
    COUNT(yobi_4_2b) as filled_yobi_4_2b,
    ROUND(COUNT(yobi_4_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_2b,
    COUNT(yobi_4_2c) as filled_yobi_4_2c,
    ROUND(COUNT(yobi_4_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_2c,
    COUNT(yobi_4_3a) as filled_yobi_4_3a,
    ROUND(COUNT(yobi_4_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_3a,
    COUNT(yobi_4_3b) as filled_yobi_4_3b,
    ROUND(COUNT(yobi_4_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_3b,
    COUNT(yobi_4_3c) as filled_yobi_4_3c,
    ROUND(COUNT(yobi_4_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_yobi_4_3c,
    COUNT(haraimodoshi_umatan_1a) as filled_haraimodoshi_umatan_1a,
    ROUND(COUNT(haraimodoshi_umatan_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_1a,
    COUNT(haraimodoshi_umatan_1b) as filled_haraimodoshi_umatan_1b,
    ROUND(COUNT(haraimodoshi_umatan_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_1b,
    COUNT(haraimodoshi_umatan_1c) as filled_haraimodoshi_umatan_1c,
    ROUND(COUNT(haraimodoshi_umatan_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_1c,
    COUNT(haraimodoshi_umatan_2a) as filled_haraimodoshi_umatan_2a,
    ROUND(COUNT(haraimodoshi_umatan_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_2a,
    COUNT(haraimodoshi_umatan_2b) as filled_haraimodoshi_umatan_2b,
    ROUND(COUNT(haraimodoshi_umatan_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_2b,
    COUNT(haraimodoshi_umatan_2c) as filled_haraimodoshi_umatan_2c,
    ROUND(COUNT(haraimodoshi_umatan_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_2c,
    COUNT(haraimodoshi_umatan_3a) as filled_haraimodoshi_umatan_3a,
    ROUND(COUNT(haraimodoshi_umatan_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_3a,
    COUNT(haraimodoshi_umatan_3b) as filled_haraimodoshi_umatan_3b,
    ROUND(COUNT(haraimodoshi_umatan_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_3b,
    COUNT(haraimodoshi_umatan_3c) as filled_haraimodoshi_umatan_3c,
    ROUND(COUNT(haraimodoshi_umatan_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_3c,
    COUNT(haraimodoshi_umatan_4a) as filled_haraimodoshi_umatan_4a,
    ROUND(COUNT(haraimodoshi_umatan_4a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_4a,
    COUNT(haraimodoshi_umatan_4b) as filled_haraimodoshi_umatan_4b,
    ROUND(COUNT(haraimodoshi_umatan_4b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_4b,
    COUNT(haraimodoshi_umatan_4c) as filled_haraimodoshi_umatan_4c,
    ROUND(COUNT(haraimodoshi_umatan_4c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_4c,
    COUNT(haraimodoshi_umatan_5a) as filled_haraimodoshi_umatan_5a,
    ROUND(COUNT(haraimodoshi_umatan_5a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_5a,
    COUNT(haraimodoshi_umatan_5b) as filled_haraimodoshi_umatan_5b,
    ROUND(COUNT(haraimodoshi_umatan_5b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_5b,
    COUNT(haraimodoshi_umatan_5c) as filled_haraimodoshi_umatan_5c,
    ROUND(COUNT(haraimodoshi_umatan_5c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_5c,
    COUNT(haraimodoshi_umatan_6a) as filled_haraimodoshi_umatan_6a,
    ROUND(COUNT(haraimodoshi_umatan_6a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_6a,
    COUNT(haraimodoshi_umatan_6b) as filled_haraimodoshi_umatan_6b,
    ROUND(COUNT(haraimodoshi_umatan_6b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_6b,
    COUNT(haraimodoshi_umatan_6c) as filled_haraimodoshi_umatan_6c,
    ROUND(COUNT(haraimodoshi_umatan_6c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_umatan_6c,
    COUNT(haraimodoshi_sanrenpuku_1a) as filled_haraimodoshi_sanrenpuku_1a,
    ROUND(COUNT(haraimodoshi_sanrenpuku_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_1a,
    COUNT(haraimodoshi_sanrenpuku_1b) as filled_haraimodoshi_sanrenpuku_1b,
    ROUND(COUNT(haraimodoshi_sanrenpuku_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_1b,
    COUNT(haraimodoshi_sanrenpuku_1c) as filled_haraimodoshi_sanrenpuku_1c,
    ROUND(COUNT(haraimodoshi_sanrenpuku_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_1c,
    COUNT(haraimodoshi_sanrenpuku_2a) as filled_haraimodoshi_sanrenpuku_2a,
    ROUND(COUNT(haraimodoshi_sanrenpuku_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_2a,
    COUNT(haraimodoshi_sanrenpuku_2b) as filled_haraimodoshi_sanrenpuku_2b,
    ROUND(COUNT(haraimodoshi_sanrenpuku_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_2b,
    COUNT(haraimodoshi_sanrenpuku_2c) as filled_haraimodoshi_sanrenpuku_2c,
    ROUND(COUNT(haraimodoshi_sanrenpuku_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_2c,
    COUNT(haraimodoshi_sanrenpuku_3a) as filled_haraimodoshi_sanrenpuku_3a,
    ROUND(COUNT(haraimodoshi_sanrenpuku_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_3a,
    COUNT(haraimodoshi_sanrenpuku_3b) as filled_haraimodoshi_sanrenpuku_3b,
    ROUND(COUNT(haraimodoshi_sanrenpuku_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_3b,
    COUNT(haraimodoshi_sanrenpuku_3c) as filled_haraimodoshi_sanrenpuku_3c,
    ROUND(COUNT(haraimodoshi_sanrenpuku_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrenpuku_3c,
    COUNT(haraimodoshi_sanrentan_1a) as filled_haraimodoshi_sanrentan_1a,
    ROUND(COUNT(haraimodoshi_sanrentan_1a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_1a,
    COUNT(haraimodoshi_sanrentan_1b) as filled_haraimodoshi_sanrentan_1b,
    ROUND(COUNT(haraimodoshi_sanrentan_1b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_1b,
    COUNT(haraimodoshi_sanrentan_1c) as filled_haraimodoshi_sanrentan_1c,
    ROUND(COUNT(haraimodoshi_sanrentan_1c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_1c,
    COUNT(haraimodoshi_sanrentan_2a) as filled_haraimodoshi_sanrentan_2a,
    ROUND(COUNT(haraimodoshi_sanrentan_2a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_2a,
    COUNT(haraimodoshi_sanrentan_2b) as filled_haraimodoshi_sanrentan_2b,
    ROUND(COUNT(haraimodoshi_sanrentan_2b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_2b,
    COUNT(haraimodoshi_sanrentan_2c) as filled_haraimodoshi_sanrentan_2c,
    ROUND(COUNT(haraimodoshi_sanrentan_2c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_2c,
    COUNT(haraimodoshi_sanrentan_3a) as filled_haraimodoshi_sanrentan_3a,
    ROUND(COUNT(haraimodoshi_sanrentan_3a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_3a,
    COUNT(haraimodoshi_sanrentan_3b) as filled_haraimodoshi_sanrentan_3b,
    ROUND(COUNT(haraimodoshi_sanrentan_3b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_3b,
    COUNT(haraimodoshi_sanrentan_3c) as filled_haraimodoshi_sanrentan_3c,
    ROUND(COUNT(haraimodoshi_sanrentan_3c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_3c,
    COUNT(haraimodoshi_sanrentan_4a) as filled_haraimodoshi_sanrentan_4a,
    ROUND(COUNT(haraimodoshi_sanrentan_4a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_4a,
    COUNT(haraimodoshi_sanrentan_4b) as filled_haraimodoshi_sanrentan_4b,
    ROUND(COUNT(haraimodoshi_sanrentan_4b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_4b,
    COUNT(haraimodoshi_sanrentan_4c) as filled_haraimodoshi_sanrentan_4c,
    ROUND(COUNT(haraimodoshi_sanrentan_4c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_4c,
    COUNT(haraimodoshi_sanrentan_5a) as filled_haraimodoshi_sanrentan_5a,
    ROUND(COUNT(haraimodoshi_sanrentan_5a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_5a,
    COUNT(haraimodoshi_sanrentan_5b) as filled_haraimodoshi_sanrentan_5b,
    ROUND(COUNT(haraimodoshi_sanrentan_5b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_5b,
    COUNT(haraimodoshi_sanrentan_5c) as filled_haraimodoshi_sanrentan_5c,
    ROUND(COUNT(haraimodoshi_sanrentan_5c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_5c,
    COUNT(haraimodoshi_sanrentan_6a) as filled_haraimodoshi_sanrentan_6a,
    ROUND(COUNT(haraimodoshi_sanrentan_6a)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_6a,
    COUNT(haraimodoshi_sanrentan_6b) as filled_haraimodoshi_sanrentan_6b,
    ROUND(COUNT(haraimodoshi_sanrentan_6b)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_6b,
    COUNT(haraimodoshi_sanrentan_6c) as filled_haraimodoshi_sanrentan_6c,
    ROUND(COUNT(haraimodoshi_sanrentan_6c)::NUMERIC / COUNT(*) * 100, 2) as fillrate_haraimodoshi_sanrentan_6c
FROM jvd_hr
WHERE kaisai_nen BETWEEN '2016' AND '2025';


-- ============================================================
-- JVD_CK (100カラム, 483,981行)
-- ============================================================

SELECT 
    'jvd_ck' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(ketto_toroku_bango) as filled_ketto_toroku_bango,
    ROUND(COUNT(ketto_toroku_bango)::NUMERIC / COUNT(*) * 100, 2) as fillrate_ketto_toroku_bango,
    COUNT(bamei) as filled_bamei,
    ROUND(COUNT(bamei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_bamei,
    COUNT(heichi_honshokin_ruikei) as filled_heichi_honshokin_ruikei,
    ROUND(COUNT(heichi_honshokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_heichi_honshokin_ruikei,
    COUNT(shogai_honshokin_ruikei) as filled_shogai_honshokin_ruikei,
    ROUND(COUNT(shogai_honshokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_honshokin_ruikei,
    COUNT(heichi_fukashokin_ruikei) as filled_heichi_fukashokin_ruikei,
    ROUND(COUNT(heichi_fukashokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_heichi_fukashokin_ruikei,
    COUNT(shogai_fukashokin_ruikei) as filled_shogai_fukashokin_ruikei,
    ROUND(COUNT(shogai_fukashokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_fukashokin_ruikei,
    COUNT(heichi_shutokushokin_ruikei) as filled_heichi_shutokushokin_ruikei,
    ROUND(COUNT(heichi_shutokushokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_heichi_shutokushokin_ruikei,
    COUNT(shogai_shutokushokin_ruikei) as filled_shogai_shutokushokin_ruikei,
    ROUND(COUNT(shogai_shutokushokin_ruikei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_shutokushokin_ruikei,
    COUNT(sogo) as filled_sogo,
    ROUND(COUNT(sogo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_sogo,
    COUNT(chuo_gokei) as filled_chuo_gokei,
    ROUND(COUNT(chuo_gokei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chuo_gokei,
    COUNT(shiba_choku) as filled_shiba_choku,
    ROUND(COUNT(shiba_choku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_choku,
    COUNT(shiba_migi) as filled_shiba_migi,
    ROUND(COUNT(shiba_migi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_migi,
    COUNT(shiba_hidari) as filled_shiba_hidari,
    ROUND(COUNT(shiba_hidari)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_hidari,
    COUNT(dirt_choku) as filled_dirt_choku,
    ROUND(COUNT(dirt_choku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_choku,
    COUNT(dirt_migi) as filled_dirt_migi,
    ROUND(COUNT(dirt_migi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_migi,
    COUNT(dirt_hidari) as filled_dirt_hidari,
    ROUND(COUNT(dirt_hidari)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_hidari,
    COUNT(shogai) as filled_shogai,
    ROUND(COUNT(shogai)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai,
    COUNT(shiba_ryo) as filled_shiba_ryo,
    ROUND(COUNT(shiba_ryo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_ryo,
    COUNT(shiba_yayaomo) as filled_shiba_yayaomo,
    ROUND(COUNT(shiba_yayaomo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_yayaomo,
    COUNT(shiba_omo) as filled_shiba_omo,
    ROUND(COUNT(shiba_omo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_omo,
    COUNT(shiba_furyo) as filled_shiba_furyo,
    ROUND(COUNT(shiba_furyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_furyo,
    COUNT(dirt_ryo) as filled_dirt_ryo,
    ROUND(COUNT(dirt_ryo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_ryo,
    COUNT(dirt_yayaomo) as filled_dirt_yayaomo,
    ROUND(COUNT(dirt_yayaomo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_yayaomo,
    COUNT(dirt_omo) as filled_dirt_omo,
    ROUND(COUNT(dirt_omo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_omo,
    COUNT(dirt_furyo) as filled_dirt_furyo,
    ROUND(COUNT(dirt_furyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_furyo,
    COUNT(shogai_ryo) as filled_shogai_ryo,
    ROUND(COUNT(shogai_ryo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_ryo,
    COUNT(shogai_yayaomo) as filled_shogai_yayaomo,
    ROUND(COUNT(shogai_yayaomo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_yayaomo,
    COUNT(shogai_omo) as filled_shogai_omo,
    ROUND(COUNT(shogai_omo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_omo,
    COUNT(shogai_furyo) as filled_shogai_furyo,
    ROUND(COUNT(shogai_furyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_furyo,
    COUNT(shiba_1200_ika) as filled_shiba_1200_ika,
    ROUND(COUNT(shiba_1200_ika)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_1200_ika,
    COUNT(shiba_1201_1400) as filled_shiba_1201_1400,
    ROUND(COUNT(shiba_1201_1400)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_1201_1400,
    COUNT(shiba_1401_1600) as filled_shiba_1401_1600,
    ROUND(COUNT(shiba_1401_1600)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_1401_1600,
    COUNT(shiba_1601_1800) as filled_shiba_1601_1800,
    ROUND(COUNT(shiba_1601_1800)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_1601_1800,
    COUNT(shiba_1801_2000) as filled_shiba_1801_2000,
    ROUND(COUNT(shiba_1801_2000)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_1801_2000,
    COUNT(shiba_2001_2200) as filled_shiba_2001_2200,
    ROUND(COUNT(shiba_2001_2200)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_2001_2200,
    COUNT(shiba_2201_2400) as filled_shiba_2201_2400,
    ROUND(COUNT(shiba_2201_2400)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_2201_2400,
    COUNT(shiba_2401_2800) as filled_shiba_2401_2800,
    ROUND(COUNT(shiba_2401_2800)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_2401_2800,
    COUNT(shiba_2801_ijo) as filled_shiba_2801_ijo,
    ROUND(COUNT(shiba_2801_ijo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_2801_ijo,
    COUNT(dirt_1200_ika) as filled_dirt_1200_ika,
    ROUND(COUNT(dirt_1200_ika)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_1200_ika,
    COUNT(dirt_1201_1400) as filled_dirt_1201_1400,
    ROUND(COUNT(dirt_1201_1400)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_1201_1400,
    COUNT(dirt_1401_1600) as filled_dirt_1401_1600,
    ROUND(COUNT(dirt_1401_1600)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_1401_1600,
    COUNT(dirt_1601_1800) as filled_dirt_1601_1800,
    ROUND(COUNT(dirt_1601_1800)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_1601_1800,
    COUNT(dirt_1801_2000) as filled_dirt_1801_2000,
    ROUND(COUNT(dirt_1801_2000)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_1801_2000,
    COUNT(dirt_2001_2200) as filled_dirt_2001_2200,
    ROUND(COUNT(dirt_2001_2200)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_2001_2200,
    COUNT(dirt_2201_2400) as filled_dirt_2201_2400,
    ROUND(COUNT(dirt_2201_2400)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_2201_2400,
    COUNT(dirt_2401_2800) as filled_dirt_2401_2800,
    ROUND(COUNT(dirt_2401_2800)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_2401_2800,
    COUNT(dirt_2801_ijo) as filled_dirt_2801_ijo,
    ROUND(COUNT(dirt_2801_ijo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_2801_ijo,
    COUNT(shiba_sapporo) as filled_shiba_sapporo,
    ROUND(COUNT(shiba_sapporo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_sapporo,
    COUNT(shiba_hakodate) as filled_shiba_hakodate,
    ROUND(COUNT(shiba_hakodate)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_hakodate,
    COUNT(shiba_fukushima) as filled_shiba_fukushima,
    ROUND(COUNT(shiba_fukushima)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_fukushima,
    COUNT(shiba_niigata) as filled_shiba_niigata,
    ROUND(COUNT(shiba_niigata)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_niigata,
    COUNT(shiba_tokyo) as filled_shiba_tokyo,
    ROUND(COUNT(shiba_tokyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_tokyo,
    COUNT(shiba_nakayama) as filled_shiba_nakayama,
    ROUND(COUNT(shiba_nakayama)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_nakayama,
    COUNT(shiba_chukyo) as filled_shiba_chukyo,
    ROUND(COUNT(shiba_chukyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_chukyo,
    COUNT(shiba_kyoto) as filled_shiba_kyoto,
    ROUND(COUNT(shiba_kyoto)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_kyoto,
    COUNT(shiba_hanshin) as filled_shiba_hanshin,
    ROUND(COUNT(shiba_hanshin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_hanshin,
    COUNT(shiba_kokura) as filled_shiba_kokura,
    ROUND(COUNT(shiba_kokura)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shiba_kokura,
    COUNT(dirt_sapporo) as filled_dirt_sapporo,
    ROUND(COUNT(dirt_sapporo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_sapporo,
    COUNT(dirt_hakodate) as filled_dirt_hakodate,
    ROUND(COUNT(dirt_hakodate)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_hakodate,
    COUNT(dirt_fukushima) as filled_dirt_fukushima,
    ROUND(COUNT(dirt_fukushima)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_fukushima,
    COUNT(dirt_niigata) as filled_dirt_niigata,
    ROUND(COUNT(dirt_niigata)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_niigata,
    COUNT(dirt_tokyo) as filled_dirt_tokyo,
    ROUND(COUNT(dirt_tokyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_tokyo,
    COUNT(dirt_nakayama) as filled_dirt_nakayama,
    ROUND(COUNT(dirt_nakayama)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_nakayama,
    COUNT(dirt_chukyo) as filled_dirt_chukyo,
    ROUND(COUNT(dirt_chukyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_chukyo,
    COUNT(dirt_kyoto) as filled_dirt_kyoto,
    ROUND(COUNT(dirt_kyoto)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_kyoto,
    COUNT(dirt_hanshin) as filled_dirt_hanshin,
    ROUND(COUNT(dirt_hanshin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_hanshin,
    COUNT(dirt_kokura) as filled_dirt_kokura,
    ROUND(COUNT(dirt_kokura)::NUMERIC / COUNT(*) * 100, 2) as fillrate_dirt_kokura,
    COUNT(shogai_sapporo) as filled_shogai_sapporo,
    ROUND(COUNT(shogai_sapporo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_sapporo,
    COUNT(shogai_hakodate) as filled_shogai_hakodate,
    ROUND(COUNT(shogai_hakodate)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_hakodate,
    COUNT(shogai_fukushima) as filled_shogai_fukushima,
    ROUND(COUNT(shogai_fukushima)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_fukushima,
    COUNT(shogai_niigata) as filled_shogai_niigata,
    ROUND(COUNT(shogai_niigata)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_niigata,
    COUNT(shogai_tokyo) as filled_shogai_tokyo,
    ROUND(COUNT(shogai_tokyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_tokyo,
    COUNT(shogai_nakayama) as filled_shogai_nakayama,
    ROUND(COUNT(shogai_nakayama)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_nakayama,
    COUNT(shogai_chukyo) as filled_shogai_chukyo,
    ROUND(COUNT(shogai_chukyo)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_chukyo,
    COUNT(shogai_kyoto) as filled_shogai_kyoto,
    ROUND(COUNT(shogai_kyoto)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_kyoto,
    COUNT(shogai_hanshin) as filled_shogai_hanshin,
    ROUND(COUNT(shogai_hanshin)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_hanshin,
    COUNT(shogai_kokura) as filled_shogai_kokura,
    ROUND(COUNT(shogai_kokura)::NUMERIC / COUNT(*) * 100, 2) as fillrate_shogai_kokura,
    COUNT(kyakushitsu_keiko) as filled_kyakushitsu_keiko,
    ROUND(COUNT(kyakushitsu_keiko)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kyakushitsu_keiko,
    COUNT(toroku_race_su) as filled_toroku_race_su,
    ROUND(COUNT(toroku_race_su)::NUMERIC / COUNT(*) * 100, 2) as fillrate_toroku_race_su,
    COUNT(kishu_code) as filled_kishu_code,
    ROUND(COUNT(kishu_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishu_code,
    COUNT(kishumei) as filled_kishumei,
    ROUND(COUNT(kishumei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_kishumei,
    COUNT(seiseki_joho_kishu_1) as filled_seiseki_joho_kishu_1,
    ROUND(COUNT(seiseki_joho_kishu_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_kishu_1,
    COUNT(seiseki_joho_kishu_2) as filled_seiseki_joho_kishu_2,
    ROUND(COUNT(seiseki_joho_kishu_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_kishu_2,
    COUNT(chokyoshi_code) as filled_chokyoshi_code,
    ROUND(COUNT(chokyoshi_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chokyoshi_code,
    COUNT(chokyoshimei) as filled_chokyoshimei,
    ROUND(COUNT(chokyoshimei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_chokyoshimei,
    COUNT(seiseki_joho_chokyoshi_1) as filled_seiseki_joho_chokyoshi_1,
    ROUND(COUNT(seiseki_joho_chokyoshi_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_chokyoshi_1,
    COUNT(seiseki_joho_chokyoshi_2) as filled_seiseki_joho_chokyoshi_2,
    ROUND(COUNT(seiseki_joho_chokyoshi_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_chokyoshi_2,
    COUNT(banushi_code) as filled_banushi_code,
    ROUND(COUNT(banushi_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_banushi_code,
    COUNT(banushimei_hojinkaku) as filled_banushimei_hojinkaku,
    ROUND(COUNT(banushimei_hojinkaku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_banushimei_hojinkaku,
    COUNT(banushimei) as filled_banushimei,
    ROUND(COUNT(banushimei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_banushimei,
    COUNT(seiseki_joho_banushi_1) as filled_seiseki_joho_banushi_1,
    ROUND(COUNT(seiseki_joho_banushi_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_banushi_1,
    COUNT(seiseki_joho_banushi_2) as filled_seiseki_joho_banushi_2,
    ROUND(COUNT(seiseki_joho_banushi_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_banushi_2,
    COUNT(seisansha_code) as filled_seisansha_code,
    ROUND(COUNT(seisansha_code)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seisansha_code,
    COUNT(seisanshamei_hojinkaku) as filled_seisanshamei_hojinkaku,
    ROUND(COUNT(seisanshamei_hojinkaku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seisanshamei_hojinkaku,
    COUNT(seisanshamei) as filled_seisanshamei,
    ROUND(COUNT(seisanshamei)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seisanshamei,
    COUNT(seiseki_joho_seisansha_1) as filled_seiseki_joho_seisansha_1,
    ROUND(COUNT(seiseki_joho_seisansha_1)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_seisansha_1,
    COUNT(seiseki_joho_seisansha_2) as filled_seiseki_joho_seisansha_2,
    ROUND(COUNT(seiseki_joho_seisansha_2)::NUMERIC / COUNT(*) * 100, 2) as fillrate_seiseki_joho_seisansha_2
FROM jvd_ck
WHERE kaisai_nen BETWEEN '2016' AND '2025';


-- ============================================================
-- JVD_H1 (36カラム, 34,516行)
-- ============================================================

SELECT 
    'jvd_h1' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(toroku_tosu) as filled_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) as fillrate_toroku_tosu,
    COUNT(hatsubai_flag_tansho) as filled_hatsubai_flag_tansho,
    ROUND(COUNT(hatsubai_flag_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_tansho,
    COUNT(hatsubai_flag_fukusho) as filled_hatsubai_flag_fukusho,
    ROUND(COUNT(hatsubai_flag_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_fukusho,
    COUNT(hatsubai_flag_wakuren) as filled_hatsubai_flag_wakuren,
    ROUND(COUNT(hatsubai_flag_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_wakuren,
    COUNT(hatsubai_flag_umaren) as filled_hatsubai_flag_umaren,
    ROUND(COUNT(hatsubai_flag_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_umaren,
    COUNT(hatsubai_flag_wide) as filled_hatsubai_flag_wide,
    ROUND(COUNT(hatsubai_flag_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_wide,
    COUNT(hatsubai_flag_umatan) as filled_hatsubai_flag_umatan,
    ROUND(COUNT(hatsubai_flag_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_umatan,
    COUNT(hatsubai_flag_sanrenpuku) as filled_hatsubai_flag_sanrenpuku,
    ROUND(COUNT(hatsubai_flag_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_sanrenpuku,
    COUNT(fukusho_chakubarai_key) as filled_fukusho_chakubarai_key,
    ROUND(COUNT(fukusho_chakubarai_key)::NUMERIC / COUNT(*) * 100, 2) as fillrate_fukusho_chakubarai_key,
    COUNT(henkan_umaban_joho) as filled_henkan_umaban_joho,
    ROUND(COUNT(henkan_umaban_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_umaban_joho,
    COUNT(henkan_wakuban_joho) as filled_henkan_wakuban_joho,
    ROUND(COUNT(henkan_wakuban_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_wakuban_joho,
    COUNT(henkan_dowaku_joho) as filled_henkan_dowaku_joho,
    ROUND(COUNT(henkan_dowaku_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_dowaku_joho,
    COUNT(hyosu_tansho) as filled_hyosu_tansho,
    ROUND(COUNT(hyosu_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_tansho,
    COUNT(hyosu_fukusho) as filled_hyosu_fukusho,
    ROUND(COUNT(hyosu_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_fukusho,
    COUNT(hyosu_wakuren) as filled_hyosu_wakuren,
    ROUND(COUNT(hyosu_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_wakuren,
    COUNT(hyosu_umaren) as filled_hyosu_umaren,
    ROUND(COUNT(hyosu_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_umaren,
    COUNT(hyosu_wide) as filled_hyosu_wide,
    ROUND(COUNT(hyosu_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_wide,
    COUNT(hyosu_umatan) as filled_hyosu_umatan,
    ROUND(COUNT(hyosu_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_umatan,
    COUNT(hyosu_sanrenpuku) as filled_hyosu_sanrenpuku,
    ROUND(COUNT(hyosu_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_sanrenpuku,
    COUNT(hyosu_gokei_tansho) as filled_hyosu_gokei_tansho,
    ROUND(COUNT(hyosu_gokei_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_tansho,
    COUNT(hyosu_gokei_fukusho) as filled_hyosu_gokei_fukusho,
    ROUND(COUNT(hyosu_gokei_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_fukusho,
    COUNT(hyosu_gokei_wakuren) as filled_hyosu_gokei_wakuren,
    ROUND(COUNT(hyosu_gokei_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_wakuren,
    COUNT(hyosu_gokei_umaren) as filled_hyosu_gokei_umaren,
    ROUND(COUNT(hyosu_gokei_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_umaren,
    COUNT(hyosu_gokei_wide) as filled_hyosu_gokei_wide,
    ROUND(COUNT(hyosu_gokei_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_wide,
    COUNT(hyosu_gokei_umatan) as filled_hyosu_gokei_umatan,
    ROUND(COUNT(hyosu_gokei_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_umatan,
    COUNT(hyosu_gokei_sanrenpuku) as filled_hyosu_gokei_sanrenpuku,
    ROUND(COUNT(hyosu_gokei_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_sanrenpuku,
    COUNT(henkan_hyosu_gokei_tansho) as filled_henkan_hyosu_gokei_tansho,
    ROUND(COUNT(henkan_hyosu_gokei_tansho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_tansho,
    COUNT(henkan_hyosu_gokei_fukusho) as filled_henkan_hyosu_gokei_fukusho,
    ROUND(COUNT(henkan_hyosu_gokei_fukusho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_fukusho,
    COUNT(henkan_hyosu_gokei_wakuren) as filled_henkan_hyosu_gokei_wakuren,
    ROUND(COUNT(henkan_hyosu_gokei_wakuren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_wakuren,
    COUNT(henkan_hyosu_gokei_umaren) as filled_henkan_hyosu_gokei_umaren,
    ROUND(COUNT(henkan_hyosu_gokei_umaren)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_umaren,
    COUNT(henkan_hyosu_gokei_wide) as filled_henkan_hyosu_gokei_wide,
    ROUND(COUNT(henkan_hyosu_gokei_wide)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_wide,
    COUNT(henkan_hyosu_gokei_umatan) as filled_henkan_hyosu_gokei_umatan,
    ROUND(COUNT(henkan_hyosu_gokei_umatan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_umatan,
    COUNT(henkan_hyosu_gokei_sanrenpuku) as filled_henkan_hyosu_gokei_sanrenpuku,
    ROUND(COUNT(henkan_hyosu_gokei_sanrenpuku)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_sanrenpuku
FROM jvd_h1
WHERE kaisai_nen BETWEEN '2016' AND '2025';


-- ============================================================
-- JVD_H6 (9カラム, 34,516行)
-- ============================================================

SELECT 
    'jvd_h6' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(toroku_tosu) as filled_toroku_tosu,
    ROUND(COUNT(toroku_tosu)::NUMERIC / COUNT(*) * 100, 2) as fillrate_toroku_tosu,
    COUNT(hatsubai_flag_sanrentan) as filled_hatsubai_flag_sanrentan,
    ROUND(COUNT(hatsubai_flag_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hatsubai_flag_sanrentan,
    COUNT(henkan_umaban_joho) as filled_henkan_umaban_joho,
    ROUND(COUNT(henkan_umaban_joho)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_umaban_joho,
    COUNT(hyosu_sanrentan) as filled_hyosu_sanrentan,
    ROUND(COUNT(hyosu_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_sanrentan,
    COUNT(hyosu_gokei_sanrentan) as filled_hyosu_gokei_sanrentan,
    ROUND(COUNT(hyosu_gokei_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_hyosu_gokei_sanrentan,
    COUNT(henkan_hyosu_gokei_sanrentan) as filled_henkan_hyosu_gokei_sanrentan,
    ROUND(COUNT(henkan_hyosu_gokei_sanrentan)::NUMERIC / COUNT(*) * 100, 2) as fillrate_henkan_hyosu_gokei_sanrentan
FROM jvd_h6
WHERE kaisai_nen BETWEEN '2016' AND '2025';


-- ============================================================
-- JVD_DM (22カラム, 34,548行)
-- ============================================================

SELECT 
    'jvd_dm' as table_name,
    COUNT(*) as total_rows,
    COUNT(record_id) as filled_record_id,
    ROUND(COUNT(record_id)::NUMERIC / COUNT(*) * 100, 2) as fillrate_record_id,
    COUNT(data_kubun) as filled_data_kubun,
    ROUND(COUNT(data_kubun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_kubun,
    COUNT(data_sakusei_nengappi) as filled_data_sakusei_nengappi,
    ROUND(COUNT(data_sakusei_nengappi)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_nengappi,
    COUNT(data_sakusei_jifun) as filled_data_sakusei_jifun,
    ROUND(COUNT(data_sakusei_jifun)::NUMERIC / COUNT(*) * 100, 2) as fillrate_data_sakusei_jifun,
    COUNT(mining_yoso_01) as filled_mining_yoso_01,
    ROUND(COUNT(mining_yoso_01)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_01,
    COUNT(mining_yoso_02) as filled_mining_yoso_02,
    ROUND(COUNT(mining_yoso_02)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_02,
    COUNT(mining_yoso_03) as filled_mining_yoso_03,
    ROUND(COUNT(mining_yoso_03)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_03,
    COUNT(mining_yoso_04) as filled_mining_yoso_04,
    ROUND(COUNT(mining_yoso_04)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_04,
    COUNT(mining_yoso_05) as filled_mining_yoso_05,
    ROUND(COUNT(mining_yoso_05)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_05,
    COUNT(mining_yoso_06) as filled_mining_yoso_06,
    ROUND(COUNT(mining_yoso_06)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_06,
    COUNT(mining_yoso_07) as filled_mining_yoso_07,
    ROUND(COUNT(mining_yoso_07)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_07,
    COUNT(mining_yoso_08) as filled_mining_yoso_08,
    ROUND(COUNT(mining_yoso_08)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_08,
    COUNT(mining_yoso_09) as filled_mining_yoso_09,
    ROUND(COUNT(mining_yoso_09)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_09,
    COUNT(mining_yoso_10) as filled_mining_yoso_10,
    ROUND(COUNT(mining_yoso_10)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_10,
    COUNT(mining_yoso_11) as filled_mining_yoso_11,
    ROUND(COUNT(mining_yoso_11)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_11,
    COUNT(mining_yoso_12) as filled_mining_yoso_12,
    ROUND(COUNT(mining_yoso_12)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_12,
    COUNT(mining_yoso_13) as filled_mining_yoso_13,
    ROUND(COUNT(mining_yoso_13)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_13,
    COUNT(mining_yoso_14) as filled_mining_yoso_14,
    ROUND(COUNT(mining_yoso_14)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_14,
    COUNT(mining_yoso_15) as filled_mining_yoso_15,
    ROUND(COUNT(mining_yoso_15)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_15,
    COUNT(mining_yoso_16) as filled_mining_yoso_16,
    ROUND(COUNT(mining_yoso_16)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_16,
    COUNT(mining_yoso_17) as filled_mining_yoso_17,
    ROUND(COUNT(mining_yoso_17)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_17,
    COUNT(mining_yoso_18) as filled_mining_yoso_18,
    ROUND(COUNT(mining_yoso_18)::NUMERIC / COUNT(*) * 100, 2) as fillrate_mining_yoso_18
FROM jvd_dm
WHERE kaisai_nen BETWEEN '2016' AND '2025';

